/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msbooking.client.model.AppliedPromotionDTO;
import com.ridehub.feign.msbooking.client.model.PricingSnapshotDTO;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * BookingDraftResultVM
 */
@JsonPropertyOrder({
  BookingDraftResultVM.JSON_PROPERTY_BOOKING_ID,
  BookingDraftResultVM.JSON_PROPERTY_BOOKING_CODE,
  BookingDraftResultVM.JSON_PROPERTY_STATUS,
  BookingDraftResultVM.JSON_PROPERTY_QUANTITY,
  BookingDraftResultVM.JSON_PROPERTY_TOTAL_AMOUNT,
  BookingDraftResultVM.JSON_PROPERTY_TRIP_ID,
  BookingDraftResultVM.JSON_PROPERTY_SEATS,
  BookingDraftResultVM.JSON_PROPERTY_PROMO_CODE,
  BookingDraftResultVM.JSON_PROPERTY_PRICING_SNAPSHOT,
  BookingDraftResultVM.JSON_PROPERTY_APPLIED_PROMOTION,
  BookingDraftResultVM.JSON_PROPERTY_PROMO_APPLIED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class BookingDraftResultVM implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nullable
  private Long bookingId;

  public static final String JSON_PROPERTY_BOOKING_CODE = "bookingCode";
  @jakarta.annotation.Nullable
  private String bookingCode;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @jakarta.annotation.Nullable
  private Integer quantity;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT = "totalAmount";
  @jakarta.annotation.Nullable
  private BigDecimal totalAmount;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nullable
  private Long tripId;

  public static final String JSON_PROPERTY_SEATS = "seats";
  @jakarta.annotation.Nullable
  private List<String> seats = new ArrayList<>();

  public static final String JSON_PROPERTY_PROMO_CODE = "promoCode";
  @jakarta.annotation.Nullable
  private String promoCode;

  public static final String JSON_PROPERTY_PRICING_SNAPSHOT = "pricingSnapshot";
  @jakarta.annotation.Nullable
  private PricingSnapshotDTO pricingSnapshot;

  public static final String JSON_PROPERTY_APPLIED_PROMOTION = "appliedPromotion";
  @jakarta.annotation.Nullable
  private AppliedPromotionDTO appliedPromotion;

  public static final String JSON_PROPERTY_PROMO_APPLIED = "promoApplied";
  @jakarta.annotation.Nullable
  private Boolean promoApplied;

  public BookingDraftResultVM() {
  }

  public BookingDraftResultVM bookingId(@jakarta.annotation.Nullable Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingId(@jakarta.annotation.Nullable Long bookingId) {
    this.bookingId = bookingId;
  }


  public BookingDraftResultVM bookingCode(@jakarta.annotation.Nullable String bookingCode) {
    
    this.bookingCode = bookingCode;
    return this;
  }

  /**
   * Get bookingCode
   * @return bookingCode
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BOOKING_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBookingCode() {
    return bookingCode;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingCode(@jakarta.annotation.Nullable String bookingCode) {
    this.bookingCode = bookingCode;
  }


  public BookingDraftResultVM status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public BookingDraftResultVM quantity(@jakarta.annotation.Nullable Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(@jakarta.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public BookingDraftResultVM totalAmount(@jakarta.annotation.Nullable BigDecimal totalAmount) {
    
    this.totalAmount = totalAmount;
    return this;
  }

  /**
   * Get totalAmount
   * @return totalAmount
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalAmount() {
    return totalAmount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmount(@jakarta.annotation.Nullable BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
  }


  public BookingDraftResultVM tripId(@jakarta.annotation.Nullable Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTripId(@jakarta.annotation.Nullable Long tripId) {
    this.tripId = tripId;
  }


  public BookingDraftResultVM seats(@jakarta.annotation.Nullable List<String> seats) {
    
    this.seats = seats;
    return this;
  }

  public BookingDraftResultVM addSeatsItem(String seatsItem) {
    if (this.seats == null) {
      this.seats = new ArrayList<>();
    }
    this.seats.add(seatsItem);
    return this;
  }

  /**
   * Get seats
   * @return seats
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSeats() {
    return seats;
  }


  @JsonProperty(JSON_PROPERTY_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeats(@jakarta.annotation.Nullable List<String> seats) {
    this.seats = seats;
  }


  public BookingDraftResultVM promoCode(@jakarta.annotation.Nullable String promoCode) {
    
    this.promoCode = promoCode;
    return this;
  }

  /**
   * Get promoCode
   * @return promoCode
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROMO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPromoCode() {
    return promoCode;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromoCode(@jakarta.annotation.Nullable String promoCode) {
    this.promoCode = promoCode;
  }


  public BookingDraftResultVM pricingSnapshot(@jakarta.annotation.Nullable PricingSnapshotDTO pricingSnapshot) {
    
    this.pricingSnapshot = pricingSnapshot;
    return this;
  }

  /**
   * Get pricingSnapshot
   * @return pricingSnapshot
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PRICING_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PricingSnapshotDTO getPricingSnapshot() {
    return pricingSnapshot;
  }


  @JsonProperty(JSON_PROPERTY_PRICING_SNAPSHOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricingSnapshot(@jakarta.annotation.Nullable PricingSnapshotDTO pricingSnapshot) {
    this.pricingSnapshot = pricingSnapshot;
  }


  public BookingDraftResultVM appliedPromotion(@jakarta.annotation.Nullable AppliedPromotionDTO appliedPromotion) {
    
    this.appliedPromotion = appliedPromotion;
    return this;
  }

  /**
   * Get appliedPromotion
   * @return appliedPromotion
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_APPLIED_PROMOTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppliedPromotionDTO getAppliedPromotion() {
    return appliedPromotion;
  }


  @JsonProperty(JSON_PROPERTY_APPLIED_PROMOTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppliedPromotion(@jakarta.annotation.Nullable AppliedPromotionDTO appliedPromotion) {
    this.appliedPromotion = appliedPromotion;
  }


  public BookingDraftResultVM promoApplied(@jakarta.annotation.Nullable Boolean promoApplied) {
    
    this.promoApplied = promoApplied;
    return this;
  }

  /**
   * Get promoApplied
   * @return promoApplied
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROMO_APPLIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPromoApplied() {
    return promoApplied;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_APPLIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromoApplied(@jakarta.annotation.Nullable Boolean promoApplied) {
    this.promoApplied = promoApplied;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingDraftResultVM bookingDraftResultVM = (BookingDraftResultVM) o;
    return Objects.equals(this.bookingId, bookingDraftResultVM.bookingId) &&
        Objects.equals(this.bookingCode, bookingDraftResultVM.bookingCode) &&
        Objects.equals(this.status, bookingDraftResultVM.status) &&
        Objects.equals(this.quantity, bookingDraftResultVM.quantity) &&
        Objects.equals(this.totalAmount, bookingDraftResultVM.totalAmount) &&
        Objects.equals(this.tripId, bookingDraftResultVM.tripId) &&
        Objects.equals(this.seats, bookingDraftResultVM.seats) &&
        Objects.equals(this.promoCode, bookingDraftResultVM.promoCode) &&
        Objects.equals(this.pricingSnapshot, bookingDraftResultVM.pricingSnapshot) &&
        Objects.equals(this.appliedPromotion, bookingDraftResultVM.appliedPromotion) &&
        Objects.equals(this.promoApplied, bookingDraftResultVM.promoApplied);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, bookingCode, status, quantity, totalAmount, tripId, seats, promoCode, pricingSnapshot, appliedPromotion, promoApplied);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingDraftResultVM {\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    bookingCode: ").append(toIndentedString(bookingCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    seats: ").append(toIndentedString(seats)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("    pricingSnapshot: ").append(toIndentedString(pricingSnapshot)).append("\n");
    sb.append("    appliedPromotion: ").append(toIndentedString(appliedPromotion)).append("\n");
    sb.append("    promoApplied: ").append(toIndentedString(promoApplied)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

