/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * CleanupReport
 */
@JsonPropertyOrder({
  CleanupReport.JSON_PROPERTY_TOTAL_EXPIRED_FOUND,
  CleanupReport.JSON_PROPERTY_CANCELED_COUNT,
  CleanupReport.JSON_PROPERTY_REMAINING_EXPIRED,
  CleanupReport.JSON_PROPERTY_PROCESSING_TIME_MS,
  CleanupReport.JSON_PROPERTY_START_TIME,
  CleanupReport.JSON_PROPERTY_END_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CleanupReport implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL_EXPIRED_FOUND = "totalExpiredFound";
  @jakarta.annotation.Nullable
  private Long totalExpiredFound;

  public static final String JSON_PROPERTY_CANCELED_COUNT = "canceledCount";
  @jakarta.annotation.Nullable
  private Long canceledCount;

  public static final String JSON_PROPERTY_REMAINING_EXPIRED = "remainingExpired";
  @jakarta.annotation.Nullable
  private Long remainingExpired;

  public static final String JSON_PROPERTY_PROCESSING_TIME_MS = "processingTimeMs";
  @jakarta.annotation.Nullable
  private Long processingTimeMs;

  public static final String JSON_PROPERTY_START_TIME = "startTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime startTime;

  public static final String JSON_PROPERTY_END_TIME = "endTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime endTime;

  public CleanupReport() {
  }

  public CleanupReport totalExpiredFound(@jakarta.annotation.Nullable Long totalExpiredFound) {
    
    this.totalExpiredFound = totalExpiredFound;
    return this;
  }

  /**
   * Get totalExpiredFound
   * @return totalExpiredFound
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_EXPIRED_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalExpiredFound() {
    return totalExpiredFound;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_EXPIRED_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalExpiredFound(@jakarta.annotation.Nullable Long totalExpiredFound) {
    this.totalExpiredFound = totalExpiredFound;
  }


  public CleanupReport canceledCount(@jakarta.annotation.Nullable Long canceledCount) {
    
    this.canceledCount = canceledCount;
    return this;
  }

  /**
   * Get canceledCount
   * @return canceledCount
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CANCELED_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCanceledCount() {
    return canceledCount;
  }


  @JsonProperty(JSON_PROPERTY_CANCELED_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanceledCount(@jakarta.annotation.Nullable Long canceledCount) {
    this.canceledCount = canceledCount;
  }


  public CleanupReport remainingExpired(@jakarta.annotation.Nullable Long remainingExpired) {
    
    this.remainingExpired = remainingExpired;
    return this;
  }

  /**
   * Get remainingExpired
   * @return remainingExpired
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_REMAINING_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRemainingExpired() {
    return remainingExpired;
  }


  @JsonProperty(JSON_PROPERTY_REMAINING_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemainingExpired(@jakarta.annotation.Nullable Long remainingExpired) {
    this.remainingExpired = remainingExpired;
  }


  public CleanupReport processingTimeMs(@jakarta.annotation.Nullable Long processingTimeMs) {
    
    this.processingTimeMs = processingTimeMs;
    return this;
  }

  /**
   * Get processingTimeMs
   * @return processingTimeMs
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROCESSING_TIME_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProcessingTimeMs() {
    return processingTimeMs;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSING_TIME_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessingTimeMs(@jakarta.annotation.Nullable Long processingTimeMs) {
    this.processingTimeMs = processingTimeMs;
  }


  public CleanupReport startTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(@jakarta.annotation.Nullable OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public CleanupReport endTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(@jakarta.annotation.Nullable OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanupReport cleanupReport = (CleanupReport) o;
    return Objects.equals(this.totalExpiredFound, cleanupReport.totalExpiredFound) &&
        Objects.equals(this.canceledCount, cleanupReport.canceledCount) &&
        Objects.equals(this.remainingExpired, cleanupReport.remainingExpired) &&
        Objects.equals(this.processingTimeMs, cleanupReport.processingTimeMs) &&
        Objects.equals(this.startTime, cleanupReport.startTime) &&
        Objects.equals(this.endTime, cleanupReport.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalExpiredFound, canceledCount, remainingExpired, processingTimeMs, startTime, endTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanupReport {\n");
    sb.append("    totalExpiredFound: ").append(toIndentedString(totalExpiredFound)).append("\n");
    sb.append("    canceledCount: ").append(toIndentedString(canceledCount)).append("\n");
    sb.append("    remainingExpired: ").append(toIndentedString(remainingExpired)).append("\n");
    sb.append("    processingTimeMs: ").append(toIndentedString(processingTimeMs)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

