/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * CleanupStatus
 */
@JsonPropertyOrder({
  CleanupStatus.JSON_PROPERTY_EXPIRED_BOOKINGS_COUNT,
  CleanupStatus.JSON_PROPERTY_CLEANUP_NEEDED,
  CleanupStatus.JSON_PROPERTY_CHECKED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CleanupStatus implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_EXPIRED_BOOKINGS_COUNT = "expiredBookingsCount";
  @jakarta.annotation.Nullable
  private Long expiredBookingsCount;

  public static final String JSON_PROPERTY_CLEANUP_NEEDED = "cleanupNeeded";
  @jakarta.annotation.Nullable
  private Boolean cleanupNeeded;

  public static final String JSON_PROPERTY_CHECKED_AT = "checkedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime checkedAt;

  public CleanupStatus() {
  }

  public CleanupStatus expiredBookingsCount(@jakarta.annotation.Nullable Long expiredBookingsCount) {
    
    this.expiredBookingsCount = expiredBookingsCount;
    return this;
  }

  /**
   * Get expiredBookingsCount
   * @return expiredBookingsCount
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EXPIRED_BOOKINGS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiredBookingsCount() {
    return expiredBookingsCount;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRED_BOOKINGS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiredBookingsCount(@jakarta.annotation.Nullable Long expiredBookingsCount) {
    this.expiredBookingsCount = expiredBookingsCount;
  }


  public CleanupStatus cleanupNeeded(@jakarta.annotation.Nullable Boolean cleanupNeeded) {
    
    this.cleanupNeeded = cleanupNeeded;
    return this;
  }

  /**
   * Get cleanupNeeded
   * @return cleanupNeeded
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CLEANUP_NEEDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCleanupNeeded() {
    return cleanupNeeded;
  }


  @JsonProperty(JSON_PROPERTY_CLEANUP_NEEDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCleanupNeeded(@jakarta.annotation.Nullable Boolean cleanupNeeded) {
    this.cleanupNeeded = cleanupNeeded;
  }


  public CleanupStatus checkedAt(@jakarta.annotation.Nullable OffsetDateTime checkedAt) {
    
    this.checkedAt = checkedAt;
    return this;
  }

  /**
   * Get checkedAt
   * @return checkedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CHECKED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCheckedAt() {
    return checkedAt;
  }


  @JsonProperty(JSON_PROPERTY_CHECKED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckedAt(@jakarta.annotation.Nullable OffsetDateTime checkedAt) {
    this.checkedAt = checkedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CleanupStatus cleanupStatus = (CleanupStatus) o;
    return Objects.equals(this.expiredBookingsCount, cleanupStatus.expiredBookingsCount) &&
        Objects.equals(this.cleanupNeeded, cleanupStatus.cleanupNeeded) &&
        Objects.equals(this.checkedAt, cleanupStatus.checkedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiredBookingsCount, cleanupNeeded, checkedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CleanupStatus {\n");
    sb.append("    expiredBookingsCount: ").append(toIndentedString(expiredBookingsCount)).append("\n");
    sb.append("    cleanupNeeded: ").append(toIndentedString(cleanupNeeded)).append("\n");
    sb.append("    checkedAt: ").append(toIndentedString(checkedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

