/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * CreateBookingDraftRequestVM
 */
@JsonPropertyOrder({
  CreateBookingDraftRequestVM.JSON_PROPERTY_TRIP_ID,
  CreateBookingDraftRequestVM.JSON_PROPERTY_SEATS,
  CreateBookingDraftRequestVM.JSON_PROPERTY_PROMO_CODE,
  CreateBookingDraftRequestVM.JSON_PROPERTY_CUSTOMER_ID,
  CreateBookingDraftRequestVM.JSON_PROPERTY_IDEM_KEY,
  CreateBookingDraftRequestVM.JSON_PROPERTY_HOLD_TTL_SEC
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CreateBookingDraftRequestVM implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private Long tripId;

  public static final String JSON_PROPERTY_SEATS = "seats";
  @jakarta.annotation.Nullable
  private List<@Size(min = 1)String> seats = new ArrayList<>();

  public static final String JSON_PROPERTY_PROMO_CODE = "promoCode";
  @jakarta.annotation.Nullable
  private String promoCode;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  @jakarta.annotation.Nonnull
  private Long customerId;

  public static final String JSON_PROPERTY_IDEM_KEY = "idemKey";
  @jakarta.annotation.Nonnull
  private String idemKey;

  public static final String JSON_PROPERTY_HOLD_TTL_SEC = "holdTtlSec";
  @jakarta.annotation.Nonnull
  private Integer holdTtlSec;

  public CreateBookingDraftRequestVM() {
  }

  public CreateBookingDraftRequestVM tripId(@jakarta.annotation.Nonnull Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull Long tripId) {
    this.tripId = tripId;
  }


  public CreateBookingDraftRequestVM seats(@jakarta.annotation.Nullable List<@Size(min = 1)String> seats) {
    
    this.seats = seats;
    return this;
  }

  public CreateBookingDraftRequestVM addSeatsItem(String seatsItem) {
    if (this.seats == null) {
      this.seats = new ArrayList<>();
    }
    this.seats.add(seatsItem);
    return this;
  }

  /**
   * Get seats
   * @return seats
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Size(min = 1)String> getSeats() {
    return seats;
  }


  @JsonProperty(JSON_PROPERTY_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeats(@jakarta.annotation.Nullable List<@Size(min = 1)String> seats) {
    this.seats = seats;
  }


  public CreateBookingDraftRequestVM promoCode(@jakarta.annotation.Nullable String promoCode) {
    
    this.promoCode = promoCode;
    return this;
  }

  /**
   * Get promoCode
   * @return promoCode
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROMO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPromoCode() {
    return promoCode;
  }


  @JsonProperty(JSON_PROPERTY_PROMO_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromoCode(@jakarta.annotation.Nullable String promoCode) {
    this.promoCode = promoCode;
  }


  public CreateBookingDraftRequestVM customerId(@jakarta.annotation.Nonnull Long customerId) {
    
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * @return customerId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(@jakarta.annotation.Nonnull Long customerId) {
    this.customerId = customerId;
  }


  public CreateBookingDraftRequestVM idemKey(@jakarta.annotation.Nonnull String idemKey) {
    
    this.idemKey = idemKey;
    return this;
  }

  /**
   * Get idemKey
   * @return idemKey
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_IDEM_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdemKey() {
    return idemKey;
  }


  @JsonProperty(JSON_PROPERTY_IDEM_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdemKey(@jakarta.annotation.Nonnull String idemKey) {
    this.idemKey = idemKey;
  }


  public CreateBookingDraftRequestVM holdTtlSec(@jakarta.annotation.Nonnull Integer holdTtlSec) {
    
    this.holdTtlSec = holdTtlSec;
    return this;
  }

  /**
   * Get holdTtlSec
   * @return holdTtlSec
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_HOLD_TTL_SEC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHoldTtlSec() {
    return holdTtlSec;
  }


  @JsonProperty(JSON_PROPERTY_HOLD_TTL_SEC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHoldTtlSec(@jakarta.annotation.Nonnull Integer holdTtlSec) {
    this.holdTtlSec = holdTtlSec;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBookingDraftRequestVM createBookingDraftRequestVM = (CreateBookingDraftRequestVM) o;
    return Objects.equals(this.tripId, createBookingDraftRequestVM.tripId) &&
        Objects.equals(this.seats, createBookingDraftRequestVM.seats) &&
        Objects.equals(this.promoCode, createBookingDraftRequestVM.promoCode) &&
        Objects.equals(this.customerId, createBookingDraftRequestVM.customerId) &&
        Objects.equals(this.idemKey, createBookingDraftRequestVM.idemKey) &&
        Objects.equals(this.holdTtlSec, createBookingDraftRequestVM.holdTtlSec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tripId, seats, promoCode, customerId, idemKey, holdTtlSec);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBookingDraftRequestVM {\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    seats: ").append(toIndentedString(seats)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    idemKey: ").append(toIndentedString(idemKey)).append("\n");
    sb.append("    holdTtlSec: ").append(toIndentedString(holdTtlSec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

