/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msbooking.client.model.PaymentTransactionDTO;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PaymentWebhookLogDTO
 */
@JsonPropertyOrder({
  PaymentWebhookLogDTO.JSON_PROPERTY_ID,
  PaymentWebhookLogDTO.JSON_PROPERTY_PROVIDER,
  PaymentWebhookLogDTO.JSON_PROPERTY_PAYLOAD_HASH,
  PaymentWebhookLogDTO.JSON_PROPERTY_RECEIVED_AT,
  PaymentWebhookLogDTO.JSON_PROPERTY_PROCESSING_STATUS,
  PaymentWebhookLogDTO.JSON_PROPERTY_CREATED_AT,
  PaymentWebhookLogDTO.JSON_PROPERTY_UPDATED_AT,
  PaymentWebhookLogDTO.JSON_PROPERTY_IS_DELETED,
  PaymentWebhookLogDTO.JSON_PROPERTY_DELETED_AT,
  PaymentWebhookLogDTO.JSON_PROPERTY_DELETED_BY,
  PaymentWebhookLogDTO.JSON_PROPERTY_PAYMENT_TRANSACTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PaymentWebhookLogDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nullable
  private String provider;

  public static final String JSON_PROPERTY_PAYLOAD_HASH = "payloadHash";
  @jakarta.annotation.Nonnull
  private String payloadHash;

  public static final String JSON_PROPERTY_RECEIVED_AT = "receivedAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_PROCESSING_STATUS = "processingStatus";
  @jakarta.annotation.Nullable
  private String processingStatus;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_PAYMENT_TRANSACTION = "paymentTransaction";
  @jakarta.annotation.Nonnull
  private PaymentTransactionDTO paymentTransaction;

  public PaymentWebhookLogDTO() {
  }

  public PaymentWebhookLogDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public PaymentWebhookLogDTO provider(@jakarta.annotation.Nullable String provider) {
    
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public PaymentWebhookLogDTO payloadHash(@jakarta.annotation.Nonnull String payloadHash) {
    
    this.payloadHash = payloadHash;
    return this;
  }

  /**
   * Get payloadHash
   * @return payloadHash
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_PAYLOAD_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPayloadHash() {
    return payloadHash;
  }


  @JsonProperty(JSON_PROPERTY_PAYLOAD_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayloadHash(@jakarta.annotation.Nonnull String payloadHash) {
    this.payloadHash = payloadHash;
  }


  public PaymentWebhookLogDTO receivedAt(@jakarta.annotation.Nonnull OffsetDateTime receivedAt) {
    
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(JSON_PROPERTY_RECEIVED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceivedAt(@jakarta.annotation.Nonnull OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public PaymentWebhookLogDTO processingStatus(@jakarta.annotation.Nullable String processingStatus) {
    
    this.processingStatus = processingStatus;
    return this;
  }

  /**
   * Get processingStatus
   * @return processingStatus
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=64)
  @JsonProperty(JSON_PROPERTY_PROCESSING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessingStatus() {
    return processingStatus;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessingStatus(@jakarta.annotation.Nullable String processingStatus) {
    this.processingStatus = processingStatus;
  }


  public PaymentWebhookLogDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PaymentWebhookLogDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PaymentWebhookLogDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public PaymentWebhookLogDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public PaymentWebhookLogDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public PaymentWebhookLogDTO paymentTransaction(@jakarta.annotation.Nonnull PaymentTransactionDTO paymentTransaction) {
    
    this.paymentTransaction = paymentTransaction;
    return this;
  }

  /**
   * Get paymentTransaction
   * @return paymentTransaction
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_PAYMENT_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentTransactionDTO getPaymentTransaction() {
    return paymentTransaction;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentTransaction(@jakarta.annotation.Nonnull PaymentTransactionDTO paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentWebhookLogDTO paymentWebhookLogDTO = (PaymentWebhookLogDTO) o;
    return Objects.equals(this.id, paymentWebhookLogDTO.id) &&
        Objects.equals(this.provider, paymentWebhookLogDTO.provider) &&
        Objects.equals(this.payloadHash, paymentWebhookLogDTO.payloadHash) &&
        Objects.equals(this.receivedAt, paymentWebhookLogDTO.receivedAt) &&
        Objects.equals(this.processingStatus, paymentWebhookLogDTO.processingStatus) &&
        Objects.equals(this.createdAt, paymentWebhookLogDTO.createdAt) &&
        Objects.equals(this.updatedAt, paymentWebhookLogDTO.updatedAt) &&
        Objects.equals(this.isDeleted, paymentWebhookLogDTO.isDeleted) &&
        Objects.equals(this.deletedAt, paymentWebhookLogDTO.deletedAt) &&
        Objects.equals(this.deletedBy, paymentWebhookLogDTO.deletedBy) &&
        Objects.equals(this.paymentTransaction, paymentWebhookLogDTO.paymentTransaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, provider, payloadHash, receivedAt, processingStatus, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, paymentTransaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentWebhookLogDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    payloadHash: ").append(toIndentedString(payloadHash)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    processingStatus: ").append(toIndentedString(processingStatus)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    paymentTransaction: ").append(toIndentedString(paymentTransaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

