/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msbooking.client.model.BookingDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PricingSnapshotDTO
 */
@JsonPropertyOrder({
  PricingSnapshotDTO.JSON_PROPERTY_ID,
  PricingSnapshotDTO.JSON_PROPERTY_BASE_FARE,
  PricingSnapshotDTO.JSON_PROPERTY_VEHICLE_FACTOR,
  PricingSnapshotDTO.JSON_PROPERTY_FLOOR_FACTOR,
  PricingSnapshotDTO.JSON_PROPERTY_SEAT_FACTOR,
  PricingSnapshotDTO.JSON_PROPERTY_SCHEDULE_OCCASION_FACTOR,
  PricingSnapshotDTO.JSON_PROPERTY_FINAL_PRICE,
  PricingSnapshotDTO.JSON_PROPERTY_CREATED_AT,
  PricingSnapshotDTO.JSON_PROPERTY_UPDATED_AT,
  PricingSnapshotDTO.JSON_PROPERTY_IS_DELETED,
  PricingSnapshotDTO.JSON_PROPERTY_DELETED_AT,
  PricingSnapshotDTO.JSON_PROPERTY_DELETED_BY,
  PricingSnapshotDTO.JSON_PROPERTY_BOOKING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PricingSnapshotDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_BASE_FARE = "baseFare";
  @jakarta.annotation.Nonnull
  private BigDecimal baseFare;

  public static final String JSON_PROPERTY_VEHICLE_FACTOR = "vehicleFactor";
  @jakarta.annotation.Nullable
  private BigDecimal vehicleFactor;

  public static final String JSON_PROPERTY_FLOOR_FACTOR = "floorFactor";
  @jakarta.annotation.Nullable
  private BigDecimal floorFactor;

  public static final String JSON_PROPERTY_SEAT_FACTOR = "seatFactor";
  @jakarta.annotation.Nullable
  private BigDecimal seatFactor;

  public static final String JSON_PROPERTY_SCHEDULE_OCCASION_FACTOR = "scheduleOccasionFactor";
  @jakarta.annotation.Nullable
  private BigDecimal scheduleOccasionFactor;

  public static final String JSON_PROPERTY_FINAL_PRICE = "finalPrice";
  @jakarta.annotation.Nonnull
  private BigDecimal finalPrice;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_BOOKING = "booking";
  @jakarta.annotation.Nonnull
  private BookingDTO booking;

  public PricingSnapshotDTO() {
  }

  public PricingSnapshotDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public PricingSnapshotDTO baseFare(@jakarta.annotation.Nonnull BigDecimal baseFare) {
    
    this.baseFare = baseFare;
    return this;
  }

  /**
   * Get baseFare
   * @return baseFare
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_BASE_FARE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getBaseFare() {
    return baseFare;
  }


  @JsonProperty(JSON_PROPERTY_BASE_FARE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBaseFare(@jakarta.annotation.Nonnull BigDecimal baseFare) {
    this.baseFare = baseFare;
  }


  public PricingSnapshotDTO vehicleFactor(@jakarta.annotation.Nullable BigDecimal vehicleFactor) {
    
    this.vehicleFactor = vehicleFactor;
    return this;
  }

  /**
   * Get vehicleFactor
   * @return vehicleFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_VEHICLE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVehicleFactor() {
    return vehicleFactor;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVehicleFactor(@jakarta.annotation.Nullable BigDecimal vehicleFactor) {
    this.vehicleFactor = vehicleFactor;
  }


  public PricingSnapshotDTO floorFactor(@jakarta.annotation.Nullable BigDecimal floorFactor) {
    
    this.floorFactor = floorFactor;
    return this;
  }

  /**
   * Get floorFactor
   * @return floorFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_FLOOR_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFloorFactor() {
    return floorFactor;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFloorFactor(@jakarta.annotation.Nullable BigDecimal floorFactor) {
    this.floorFactor = floorFactor;
  }


  public PricingSnapshotDTO seatFactor(@jakarta.annotation.Nullable BigDecimal seatFactor) {
    
    this.seatFactor = seatFactor;
    return this;
  }

  /**
   * Get seatFactor
   * @return seatFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSeatFactor() {
    return seatFactor;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatFactor(@jakarta.annotation.Nullable BigDecimal seatFactor) {
    this.seatFactor = seatFactor;
  }


  public PricingSnapshotDTO scheduleOccasionFactor(@jakarta.annotation.Nullable BigDecimal scheduleOccasionFactor) {
    
    this.scheduleOccasionFactor = scheduleOccasionFactor;
    return this;
  }

  /**
   * Get scheduleOccasionFactor
   * @return scheduleOccasionFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SCHEDULE_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getScheduleOccasionFactor() {
    return scheduleOccasionFactor;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduleOccasionFactor(@jakarta.annotation.Nullable BigDecimal scheduleOccasionFactor) {
    this.scheduleOccasionFactor = scheduleOccasionFactor;
  }


  public PricingSnapshotDTO finalPrice(@jakarta.annotation.Nonnull BigDecimal finalPrice) {
    
    this.finalPrice = finalPrice;
    return this;
  }

  /**
   * Get finalPrice
   * @return finalPrice
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_FINAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getFinalPrice() {
    return finalPrice;
  }


  @JsonProperty(JSON_PROPERTY_FINAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFinalPrice(@jakarta.annotation.Nonnull BigDecimal finalPrice) {
    this.finalPrice = finalPrice;
  }


  public PricingSnapshotDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PricingSnapshotDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PricingSnapshotDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public PricingSnapshotDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public PricingSnapshotDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public PricingSnapshotDTO booking(@jakarta.annotation.Nonnull BookingDTO booking) {
    
    this.booking = booking;
    return this;
  }

  /**
   * Get booking
   * @return booking
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BookingDTO getBooking() {
    return booking;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBooking(@jakarta.annotation.Nonnull BookingDTO booking) {
    this.booking = booking;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingSnapshotDTO pricingSnapshotDTO = (PricingSnapshotDTO) o;
    return Objects.equals(this.id, pricingSnapshotDTO.id) &&
        Objects.equals(this.baseFare, pricingSnapshotDTO.baseFare) &&
        Objects.equals(this.vehicleFactor, pricingSnapshotDTO.vehicleFactor) &&
        Objects.equals(this.floorFactor, pricingSnapshotDTO.floorFactor) &&
        Objects.equals(this.seatFactor, pricingSnapshotDTO.seatFactor) &&
        Objects.equals(this.scheduleOccasionFactor, pricingSnapshotDTO.scheduleOccasionFactor) &&
        Objects.equals(this.finalPrice, pricingSnapshotDTO.finalPrice) &&
        Objects.equals(this.createdAt, pricingSnapshotDTO.createdAt) &&
        Objects.equals(this.updatedAt, pricingSnapshotDTO.updatedAt) &&
        Objects.equals(this.isDeleted, pricingSnapshotDTO.isDeleted) &&
        Objects.equals(this.deletedAt, pricingSnapshotDTO.deletedAt) &&
        Objects.equals(this.deletedBy, pricingSnapshotDTO.deletedBy) &&
        Objects.equals(this.booking, pricingSnapshotDTO.booking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, baseFare, vehicleFactor, floorFactor, seatFactor, scheduleOccasionFactor, finalPrice, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, booking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingSnapshotDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    baseFare: ").append(toIndentedString(baseFare)).append("\n");
    sb.append("    vehicleFactor: ").append(toIndentedString(vehicleFactor)).append("\n");
    sb.append("    floorFactor: ").append(toIndentedString(floorFactor)).append("\n");
    sb.append("    seatFactor: ").append(toIndentedString(seatFactor)).append("\n");
    sb.append("    scheduleOccasionFactor: ").append(toIndentedString(scheduleOccasionFactor)).append("\n");
    sb.append("    finalPrice: ").append(toIndentedString(finalPrice)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

