/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * RefundRequestDTO
 */
@JsonPropertyOrder({
  RefundRequestDTO.JSON_PROPERTY_AMOUNT,
  RefundRequestDTO.JSON_PROPERTY_ORDER_INFO,
  RefundRequestDTO.JSON_PROPERTY_TRANSACTION_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RefundRequestDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private BigDecimal amount;

  public static final String JSON_PROPERTY_ORDER_INFO = "orderInfo";
  @jakarta.annotation.Nullable
  private String orderInfo;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transactionType";
  @jakarta.annotation.Nullable
  private String transactionType;

  public RefundRequestDTO() {
  }

  public RefundRequestDTO amount(@jakarta.annotation.Nonnull BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * minimum: 0.01
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid
 @DecimalMin("0.01")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
  }


  public RefundRequestDTO orderInfo(@jakarta.annotation.Nullable String orderInfo) {
    
    this.orderInfo = orderInfo;
    return this;
  }

  /**
   * Get orderInfo
   * @return orderInfo
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_ORDER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderInfo() {
    return orderInfo;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderInfo(@jakarta.annotation.Nullable String orderInfo) {
    this.orderInfo = orderInfo;
  }


  public RefundRequestDTO transactionType(@jakarta.annotation.Nullable String transactionType) {
    
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Get transactionType
   * @return transactionType
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionType(@jakarta.annotation.Nullable String transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundRequestDTO refundRequestDTO = (RefundRequestDTO) o;
    return Objects.equals(this.amount, refundRequestDTO.amount) &&
        Objects.equals(this.orderInfo, refundRequestDTO.orderInfo) &&
        Objects.equals(this.transactionType, refundRequestDTO.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, orderInfo, transactionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundRequestDTO {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    orderInfo: ").append(toIndentedString(orderInfo)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

