/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msbooking.client.model.TicketDTO;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TicketResponse
 */
@JsonPropertyOrder({
  TicketResponse.JSON_PROPERTY_TICKETS,
  TicketResponse.JSON_PROPERTY_QR_CODES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TicketResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TICKETS = "tickets";
  @jakarta.annotation.Nullable
  private List<@Valid TicketDTO> tickets = new ArrayList<>();

  public static final String JSON_PROPERTY_QR_CODES = "qrCodes";
  @jakarta.annotation.Nullable
  private List<String> qrCodes = new ArrayList<>();

  public TicketResponse() {
  }

  public TicketResponse tickets(@jakarta.annotation.Nullable List<@Valid TicketDTO> tickets) {
    
    this.tickets = tickets;
    return this;
  }

  public TicketResponse addTicketsItem(TicketDTO ticketsItem) {
    if (this.tickets == null) {
      this.tickets = new ArrayList<>();
    }
    this.tickets.add(ticketsItem);
    return this;
  }

  /**
   * Get tickets
   * @return tickets
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid TicketDTO> getTickets() {
    return tickets;
  }


  @JsonProperty(JSON_PROPERTY_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTickets(@jakarta.annotation.Nullable List<@Valid TicketDTO> tickets) {
    this.tickets = tickets;
  }


  public TicketResponse qrCodes(@jakarta.annotation.Nullable List<String> qrCodes) {
    
    this.qrCodes = qrCodes;
    return this;
  }

  public TicketResponse addQrCodesItem(String qrCodesItem) {
    if (this.qrCodes == null) {
      this.qrCodes = new ArrayList<>();
    }
    this.qrCodes.add(qrCodesItem);
    return this;
  }

  /**
   * Get qrCodes
   * @return qrCodes
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_QR_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getQrCodes() {
    return qrCodes;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCodes(@jakarta.annotation.Nullable List<String> qrCodes) {
    this.qrCodes = qrCodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketResponse ticketResponse = (TicketResponse) o;
    return Objects.equals(this.tickets, ticketResponse.tickets) &&
        Objects.equals(this.qrCodes, ticketResponse.qrCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tickets, qrCodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketResponse {\n");
    sb.append("    tickets: ").append(toIndentedString(tickets)).append("\n");
    sb.append("    qrCodes: ").append(toIndentedString(qrCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

