/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TicketExchangeRequestDTO
 */
@JsonPropertyOrder({
  TicketExchangeRequestDTO.JSON_PROPERTY_NEW_TRIP_ID,
  TicketExchangeRequestDTO.JSON_PROPERTY_NEW_ROUTE_ID,
  TicketExchangeRequestDTO.JSON_PROPERTY_NEW_SEAT_ID,
  TicketExchangeRequestDTO.JSON_PROPERTY_REASON
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TicketExchangeRequestDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NEW_TRIP_ID = "newTripId";
  @jakarta.annotation.Nonnull
  private Long newTripId;

  public static final String JSON_PROPERTY_NEW_ROUTE_ID = "newRouteId";
  @jakarta.annotation.Nonnull
  private Long newRouteId;

  public static final String JSON_PROPERTY_NEW_SEAT_ID = "newSeatId";
  @jakarta.annotation.Nonnull
  private Long newSeatId;

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nullable
  private String reason;

  public TicketExchangeRequestDTO() {
  }

  public TicketExchangeRequestDTO newTripId(@jakarta.annotation.Nonnull Long newTripId) {
    
    this.newTripId = newTripId;
    return this;
  }

  /**
   * Get newTripId
   * @return newTripId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_NEW_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getNewTripId() {
    return newTripId;
  }


  @JsonProperty(JSON_PROPERTY_NEW_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewTripId(@jakarta.annotation.Nonnull Long newTripId) {
    this.newTripId = newTripId;
  }


  public TicketExchangeRequestDTO newRouteId(@jakarta.annotation.Nonnull Long newRouteId) {
    
    this.newRouteId = newRouteId;
    return this;
  }

  /**
   * Get newRouteId
   * @return newRouteId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_NEW_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getNewRouteId() {
    return newRouteId;
  }


  @JsonProperty(JSON_PROPERTY_NEW_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewRouteId(@jakarta.annotation.Nonnull Long newRouteId) {
    this.newRouteId = newRouteId;
  }


  public TicketExchangeRequestDTO newSeatId(@jakarta.annotation.Nonnull Long newSeatId) {
    
    this.newSeatId = newSeatId;
    return this;
  }

  /**
   * Get newSeatId
   * @return newSeatId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_NEW_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getNewSeatId() {
    return newSeatId;
  }


  @JsonProperty(JSON_PROPERTY_NEW_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewSeatId(@jakarta.annotation.Nonnull Long newSeatId) {
    this.newSeatId = newSeatId;
  }


  public TicketExchangeRequestDTO reason(@jakarta.annotation.Nullable String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=500)
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@jakarta.annotation.Nullable String reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketExchangeRequestDTO ticketExchangeRequestDTO = (TicketExchangeRequestDTO) o;
    return Objects.equals(this.newTripId, ticketExchangeRequestDTO.newTripId) &&
        Objects.equals(this.newRouteId, ticketExchangeRequestDTO.newRouteId) &&
        Objects.equals(this.newSeatId, ticketExchangeRequestDTO.newSeatId) &&
        Objects.equals(this.reason, ticketExchangeRequestDTO.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newTripId, newRouteId, newSeatId, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketExchangeRequestDTO {\n");
    sb.append("    newTripId: ").append(toIndentedString(newTripId)).append("\n");
    sb.append("    newRouteId: ").append(toIndentedString(newRouteId)).append("\n");
    sb.append("    newSeatId: ").append(toIndentedString(newSeatId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

