/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msbooking.client.model.BookingDTO;
import com.ridehub.feign.msbooking.client.model.FileBookingDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TicketDTO
 */
@JsonPropertyOrder({
  TicketDTO.JSON_PROPERTY_ID,
  TicketDTO.JSON_PROPERTY_TICKET_CODE,
  TicketDTO.JSON_PROPERTY_PRICE,
  TicketDTO.JSON_PROPERTY_QR_CODE,
  TicketDTO.JSON_PROPERTY_TIME_FROM,
  TicketDTO.JSON_PROPERTY_TIME_TO,
  TicketDTO.JSON_PROPERTY_CHECKED_IN,
  TicketDTO.JSON_PROPERTY_STATUS,
  TicketDTO.JSON_PROPERTY_EXCHANGE_STATUS,
  TicketDTO.JSON_PROPERTY_REFUND_STATUS,
  TicketDTO.JSON_PROPERTY_EXCHANGE_REASON,
  TicketDTO.JSON_PROPERTY_REFUND_REASON,
  TicketDTO.JSON_PROPERTY_EXCHANGE_REQUESTED_AT,
  TicketDTO.JSON_PROPERTY_EXCHANGE_COMPLETED_AT,
  TicketDTO.JSON_PROPERTY_REFUND_REQUESTED_AT,
  TicketDTO.JSON_PROPERTY_REFUND_COMPLETED_AT,
  TicketDTO.JSON_PROPERTY_REFUND_AMOUNT,
  TicketDTO.JSON_PROPERTY_REFUND_TRANSACTION_ID,
  TicketDTO.JSON_PROPERTY_TRIP_ID,
  TicketDTO.JSON_PROPERTY_ROUTE_ID,
  TicketDTO.JSON_PROPERTY_SEAT_ID,
  TicketDTO.JSON_PROPERTY_CREATED_AT,
  TicketDTO.JSON_PROPERTY_UPDATED_AT,
  TicketDTO.JSON_PROPERTY_IS_DELETED,
  TicketDTO.JSON_PROPERTY_DELETED_AT,
  TicketDTO.JSON_PROPERTY_DELETED_BY,
  TicketDTO.JSON_PROPERTY_QR_CODE_IMG,
  TicketDTO.JSON_PROPERTY_ORIGINAL_TICKET,
  TicketDTO.JSON_PROPERTY_EXCHANGED_TICKET,
  TicketDTO.JSON_PROPERTY_BOOKING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TicketDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_TICKET_CODE = "ticketCode";
  @jakarta.annotation.Nonnull
  private String ticketCode;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nonnull
  private BigDecimal price;

  public static final String JSON_PROPERTY_QR_CODE = "qrCode";
  @jakarta.annotation.Nullable
  private String qrCode;

  public static final String JSON_PROPERTY_TIME_FROM = "timeFrom";
  @jakarta.annotation.Nullable
  private OffsetDateTime timeFrom;

  public static final String JSON_PROPERTY_TIME_TO = "timeTo";
  @jakarta.annotation.Nullable
  private OffsetDateTime timeTo;

  public static final String JSON_PROPERTY_CHECKED_IN = "checkedIn";
  @jakarta.annotation.Nullable
  private Boolean checkedIn;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AVAILABLE(String.valueOf("AVAILABLE")),
    
    BOOKED(String.valueOf("BOOKED")),
    
    CANCELLED(String.valueOf("CANCELLED")),
    
    EXPIRED(String.valueOf("EXPIRED")),
    
    EXCHANGE_REQUESTED(String.valueOf("EXCHANGE_REQUESTED")),
    
    EXCHANGE_APPROVED(String.valueOf("EXCHANGE_APPROVED")),
    
    EXCHANGE_REJECTED(String.valueOf("EXCHANGE_REJECTED")),
    
    EXCHANGE_COMPLETED(String.valueOf("EXCHANGE_COMPLETED")),
    
    REFUND_REQUESTED(String.valueOf("REFUND_REQUESTED")),
    
    REFUND_APPROVED(String.valueOf("REFUND_APPROVED")),
    
    REFUND_REJECTED(String.valueOf("REFUND_REJECTED")),
    
    REFUND_COMPLETED(String.valueOf("REFUND_COMPLETED")),
    
    REFUND_FAILED(String.valueOf("REFUND_FAILED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  /**
   * Gets or Sets exchangeStatus
   */
  public enum ExchangeStatusEnum {
    EXCHANGE_REQUESTED(String.valueOf("EXCHANGE_REQUESTED")),
    
    EXCHANGE_APPROVED(String.valueOf("EXCHANGE_APPROVED")),
    
    EXCHANGE_REJECTED(String.valueOf("EXCHANGE_REJECTED")),
    
    EXCHANGE_COMPLETED(String.valueOf("EXCHANGE_COMPLETED"));

    private String value;

    ExchangeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExchangeStatusEnum fromValue(String value) {
      for (ExchangeStatusEnum b : ExchangeStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXCHANGE_STATUS = "exchangeStatus";
  @jakarta.annotation.Nullable
  private ExchangeStatusEnum exchangeStatus;

  /**
   * Gets or Sets refundStatus
   */
  public enum RefundStatusEnum {
    REFUND_REQUESTED(String.valueOf("REFUND_REQUESTED")),
    
    REFUND_APPROVED(String.valueOf("REFUND_APPROVED")),
    
    REFUND_REJECTED(String.valueOf("REFUND_REJECTED")),
    
    REFUND_COMPLETED(String.valueOf("REFUND_COMPLETED")),
    
    REFUND_FAILED(String.valueOf("REFUND_FAILED"));

    private String value;

    RefundStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RefundStatusEnum fromValue(String value) {
      for (RefundStatusEnum b : RefundStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REFUND_STATUS = "refundStatus";
  @jakarta.annotation.Nullable
  private RefundStatusEnum refundStatus;

  public static final String JSON_PROPERTY_EXCHANGE_REASON = "exchangeReason";
  @jakarta.annotation.Nullable
  private String exchangeReason;

  public static final String JSON_PROPERTY_REFUND_REASON = "refundReason";
  @jakarta.annotation.Nullable
  private String refundReason;

  public static final String JSON_PROPERTY_EXCHANGE_REQUESTED_AT = "exchangeRequestedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime exchangeRequestedAt;

  public static final String JSON_PROPERTY_EXCHANGE_COMPLETED_AT = "exchangeCompletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime exchangeCompletedAt;

  public static final String JSON_PROPERTY_REFUND_REQUESTED_AT = "refundRequestedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime refundRequestedAt;

  public static final String JSON_PROPERTY_REFUND_COMPLETED_AT = "refundCompletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime refundCompletedAt;

  public static final String JSON_PROPERTY_REFUND_AMOUNT = "refundAmount";
  @jakarta.annotation.Nullable
  private BigDecimal refundAmount;

  public static final String JSON_PROPERTY_REFUND_TRANSACTION_ID = "refundTransactionId";
  @jakarta.annotation.Nullable
  private String refundTransactionId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private Long tripId;

  public static final String JSON_PROPERTY_ROUTE_ID = "routeId";
  @jakarta.annotation.Nonnull
  private Long routeId;

  public static final String JSON_PROPERTY_SEAT_ID = "seatId";
  @jakarta.annotation.Nonnull
  private Long seatId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_QR_CODE_IMG = "qrCodeImg";
  @jakarta.annotation.Nullable
  private FileBookingDTO qrCodeImg;

  public static final String JSON_PROPERTY_ORIGINAL_TICKET = "originalTicket";
  @jakarta.annotation.Nullable
  private TicketDTO originalTicket;

  public static final String JSON_PROPERTY_EXCHANGED_TICKET = "exchangedTicket";
  @jakarta.annotation.Nullable
  private TicketDTO exchangedTicket;

  public static final String JSON_PROPERTY_BOOKING = "booking";
  @jakarta.annotation.Nonnull
  private BookingDTO booking;

  public TicketDTO() {
  }

  public TicketDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TicketDTO ticketCode(@jakarta.annotation.Nonnull String ticketCode) {
    
    this.ticketCode = ticketCode;
    return this;
  }

  /**
   * Get ticketCode
   * @return ticketCode
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=40)
  @JsonProperty(JSON_PROPERTY_TICKET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTicketCode() {
    return ticketCode;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTicketCode(@jakarta.annotation.Nonnull String ticketCode) {
    this.ticketCode = ticketCode;
  }


  public TicketDTO price(@jakarta.annotation.Nonnull BigDecimal price) {
    
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(@jakarta.annotation.Nonnull BigDecimal price) {
    this.price = price;
  }


  public TicketDTO qrCode(@jakarta.annotation.Nullable String qrCode) {
    
    this.qrCode = qrCode;
    return this;
  }

  /**
   * Get qrCode
   * @return qrCode
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=256)
  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQrCode() {
    return qrCode;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCode(@jakarta.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
  }


  public TicketDTO timeFrom(@jakarta.annotation.Nullable OffsetDateTime timeFrom) {
    
    this.timeFrom = timeFrom;
    return this;
  }

  /**
   * Get timeFrom
   * @return timeFrom
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimeFrom() {
    return timeFrom;
  }


  @JsonProperty(JSON_PROPERTY_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrom(@jakarta.annotation.Nullable OffsetDateTime timeFrom) {
    this.timeFrom = timeFrom;
  }


  public TicketDTO timeTo(@jakarta.annotation.Nullable OffsetDateTime timeTo) {
    
    this.timeTo = timeTo;
    return this;
  }

  /**
   * Get timeTo
   * @return timeTo
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimeTo() {
    return timeTo;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeTo(@jakarta.annotation.Nullable OffsetDateTime timeTo) {
    this.timeTo = timeTo;
  }


  public TicketDTO checkedIn(@jakarta.annotation.Nullable Boolean checkedIn) {
    
    this.checkedIn = checkedIn;
    return this;
  }

  /**
   * Get checkedIn
   * @return checkedIn
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckedIn() {
    return checkedIn;
  }


  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckedIn(@jakarta.annotation.Nullable Boolean checkedIn) {
    this.checkedIn = checkedIn;
  }


  public TicketDTO status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public TicketDTO exchangeStatus(@jakarta.annotation.Nullable ExchangeStatusEnum exchangeStatus) {
    
    this.exchangeStatus = exchangeStatus;
    return this;
  }

  /**
   * Get exchangeStatus
   * @return exchangeStatus
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EXCHANGE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExchangeStatusEnum getExchangeStatus() {
    return exchangeStatus;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeStatus(@jakarta.annotation.Nullable ExchangeStatusEnum exchangeStatus) {
    this.exchangeStatus = exchangeStatus;
  }


  public TicketDTO refundStatus(@jakarta.annotation.Nullable RefundStatusEnum refundStatus) {
    
    this.refundStatus = refundStatus;
    return this;
  }

  /**
   * Get refundStatus
   * @return refundStatus
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_REFUND_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RefundStatusEnum getRefundStatus() {
    return refundStatus;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundStatus(@jakarta.annotation.Nullable RefundStatusEnum refundStatus) {
    this.refundStatus = refundStatus;
  }


  public TicketDTO exchangeReason(@jakarta.annotation.Nullable String exchangeReason) {
    
    this.exchangeReason = exchangeReason;
    return this;
  }

  /**
   * Get exchangeReason
   * @return exchangeReason
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EXCHANGE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchangeReason() {
    return exchangeReason;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeReason(@jakarta.annotation.Nullable String exchangeReason) {
    this.exchangeReason = exchangeReason;
  }


  public TicketDTO refundReason(@jakarta.annotation.Nullable String refundReason) {
    
    this.refundReason = refundReason;
    return this;
  }

  /**
   * Get refundReason
   * @return refundReason
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_REFUND_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundReason() {
    return refundReason;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundReason(@jakarta.annotation.Nullable String refundReason) {
    this.refundReason = refundReason;
  }


  public TicketDTO exchangeRequestedAt(@jakarta.annotation.Nullable OffsetDateTime exchangeRequestedAt) {
    
    this.exchangeRequestedAt = exchangeRequestedAt;
    return this;
  }

  /**
   * Get exchangeRequestedAt
   * @return exchangeRequestedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXCHANGE_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExchangeRequestedAt() {
    return exchangeRequestedAt;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeRequestedAt(@jakarta.annotation.Nullable OffsetDateTime exchangeRequestedAt) {
    this.exchangeRequestedAt = exchangeRequestedAt;
  }


  public TicketDTO exchangeCompletedAt(@jakarta.annotation.Nullable OffsetDateTime exchangeCompletedAt) {
    
    this.exchangeCompletedAt = exchangeCompletedAt;
    return this;
  }

  /**
   * Get exchangeCompletedAt
   * @return exchangeCompletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXCHANGE_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExchangeCompletedAt() {
    return exchangeCompletedAt;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeCompletedAt(@jakarta.annotation.Nullable OffsetDateTime exchangeCompletedAt) {
    this.exchangeCompletedAt = exchangeCompletedAt;
  }


  public TicketDTO refundRequestedAt(@jakarta.annotation.Nullable OffsetDateTime refundRequestedAt) {
    
    this.refundRequestedAt = refundRequestedAt;
    return this;
  }

  /**
   * Get refundRequestedAt
   * @return refundRequestedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_REFUND_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRefundRequestedAt() {
    return refundRequestedAt;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_REQUESTED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundRequestedAt(@jakarta.annotation.Nullable OffsetDateTime refundRequestedAt) {
    this.refundRequestedAt = refundRequestedAt;
  }


  public TicketDTO refundCompletedAt(@jakarta.annotation.Nullable OffsetDateTime refundCompletedAt) {
    
    this.refundCompletedAt = refundCompletedAt;
    return this;
  }

  /**
   * Get refundCompletedAt
   * @return refundCompletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_REFUND_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRefundCompletedAt() {
    return refundCompletedAt;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_COMPLETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundCompletedAt(@jakarta.annotation.Nullable OffsetDateTime refundCompletedAt) {
    this.refundCompletedAt = refundCompletedAt;
  }


  public TicketDTO refundAmount(@jakarta.annotation.Nullable BigDecimal refundAmount) {
    
    this.refundAmount = refundAmount;
    return this;
  }

  /**
   * Get refundAmount
   * @return refundAmount
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_REFUND_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRefundAmount() {
    return refundAmount;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundAmount(@jakarta.annotation.Nullable BigDecimal refundAmount) {
    this.refundAmount = refundAmount;
  }


  public TicketDTO refundTransactionId(@jakarta.annotation.Nullable String refundTransactionId) {
    
    this.refundTransactionId = refundTransactionId;
    return this;
  }

  /**
   * Get refundTransactionId
   * @return refundTransactionId
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=80)
  @JsonProperty(JSON_PROPERTY_REFUND_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundTransactionId() {
    return refundTransactionId;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundTransactionId(@jakarta.annotation.Nullable String refundTransactionId) {
    this.refundTransactionId = refundTransactionId;
  }


  public TicketDTO tripId(@jakarta.annotation.Nonnull Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull Long tripId) {
    this.tripId = tripId;
  }


  public TicketDTO routeId(@jakarta.annotation.Nonnull Long routeId) {
    
    this.routeId = routeId;
    return this;
  }

  /**
   * Get routeId
   * @return routeId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getRouteId() {
    return routeId;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteId(@jakarta.annotation.Nonnull Long routeId) {
    this.routeId = routeId;
  }


  public TicketDTO seatId(@jakarta.annotation.Nonnull Long seatId) {
    
    this.seatId = seatId;
    return this;
  }

  /**
   * Get seatId
   * @return seatId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSeatId() {
    return seatId;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatId(@jakarta.annotation.Nonnull Long seatId) {
    this.seatId = seatId;
  }


  public TicketDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TicketDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TicketDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TicketDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TicketDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public TicketDTO qrCodeImg(@jakarta.annotation.Nullable FileBookingDTO qrCodeImg) {
    
    this.qrCodeImg = qrCodeImg;
    return this;
  }

  /**
   * Get qrCodeImg
   * @return qrCodeImg
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_QR_CODE_IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FileBookingDTO getQrCodeImg() {
    return qrCodeImg;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODE_IMG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCodeImg(@jakarta.annotation.Nullable FileBookingDTO qrCodeImg) {
    this.qrCodeImg = qrCodeImg;
  }


  public TicketDTO originalTicket(@jakarta.annotation.Nullable TicketDTO originalTicket) {
    
    this.originalTicket = originalTicket;
    return this;
  }

  /**
   * Get originalTicket
   * @return originalTicket
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_ORIGINAL_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TicketDTO getOriginalTicket() {
    return originalTicket;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalTicket(@jakarta.annotation.Nullable TicketDTO originalTicket) {
    this.originalTicket = originalTicket;
  }


  public TicketDTO exchangedTicket(@jakarta.annotation.Nullable TicketDTO exchangedTicket) {
    
    this.exchangedTicket = exchangedTicket;
    return this;
  }

  /**
   * Get exchangedTicket
   * @return exchangedTicket
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXCHANGED_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TicketDTO getExchangedTicket() {
    return exchangedTicket;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGED_TICKET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangedTicket(@jakarta.annotation.Nullable TicketDTO exchangedTicket) {
    this.exchangedTicket = exchangedTicket;
  }


  public TicketDTO booking(@jakarta.annotation.Nonnull BookingDTO booking) {
    
    this.booking = booking;
    return this;
  }

  /**
   * Get booking
   * @return booking
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BookingDTO getBooking() {
    return booking;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBooking(@jakarta.annotation.Nonnull BookingDTO booking) {
    this.booking = booking;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketDTO ticketDTO = (TicketDTO) o;
    return Objects.equals(this.id, ticketDTO.id) &&
        Objects.equals(this.ticketCode, ticketDTO.ticketCode) &&
        Objects.equals(this.price, ticketDTO.price) &&
        Objects.equals(this.qrCode, ticketDTO.qrCode) &&
        Objects.equals(this.timeFrom, ticketDTO.timeFrom) &&
        Objects.equals(this.timeTo, ticketDTO.timeTo) &&
        Objects.equals(this.checkedIn, ticketDTO.checkedIn) &&
        Objects.equals(this.status, ticketDTO.status) &&
        Objects.equals(this.exchangeStatus, ticketDTO.exchangeStatus) &&
        Objects.equals(this.refundStatus, ticketDTO.refundStatus) &&
        Objects.equals(this.exchangeReason, ticketDTO.exchangeReason) &&
        Objects.equals(this.refundReason, ticketDTO.refundReason) &&
        Objects.equals(this.exchangeRequestedAt, ticketDTO.exchangeRequestedAt) &&
        Objects.equals(this.exchangeCompletedAt, ticketDTO.exchangeCompletedAt) &&
        Objects.equals(this.refundRequestedAt, ticketDTO.refundRequestedAt) &&
        Objects.equals(this.refundCompletedAt, ticketDTO.refundCompletedAt) &&
        Objects.equals(this.refundAmount, ticketDTO.refundAmount) &&
        Objects.equals(this.refundTransactionId, ticketDTO.refundTransactionId) &&
        Objects.equals(this.tripId, ticketDTO.tripId) &&
        Objects.equals(this.routeId, ticketDTO.routeId) &&
        Objects.equals(this.seatId, ticketDTO.seatId) &&
        Objects.equals(this.createdAt, ticketDTO.createdAt) &&
        Objects.equals(this.updatedAt, ticketDTO.updatedAt) &&
        Objects.equals(this.isDeleted, ticketDTO.isDeleted) &&
        Objects.equals(this.deletedAt, ticketDTO.deletedAt) &&
        Objects.equals(this.deletedBy, ticketDTO.deletedBy) &&
        Objects.equals(this.qrCodeImg, ticketDTO.qrCodeImg) &&
        Objects.equals(this.originalTicket, ticketDTO.originalTicket) &&
        Objects.equals(this.exchangedTicket, ticketDTO.exchangedTicket) &&
        Objects.equals(this.booking, ticketDTO.booking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ticketCode, price, qrCode, timeFrom, timeTo, checkedIn, status, exchangeStatus, refundStatus, exchangeReason, refundReason, exchangeRequestedAt, exchangeCompletedAt, refundRequestedAt, refundCompletedAt, refundAmount, refundTransactionId, tripId, routeId, seatId, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, qrCodeImg, originalTicket, exchangedTicket, booking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ticketCode: ").append(toIndentedString(ticketCode)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    timeFrom: ").append(toIndentedString(timeFrom)).append("\n");
    sb.append("    timeTo: ").append(toIndentedString(timeTo)).append("\n");
    sb.append("    checkedIn: ").append(toIndentedString(checkedIn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    exchangeStatus: ").append(toIndentedString(exchangeStatus)).append("\n");
    sb.append("    refundStatus: ").append(toIndentedString(refundStatus)).append("\n");
    sb.append("    exchangeReason: ").append(toIndentedString(exchangeReason)).append("\n");
    sb.append("    refundReason: ").append(toIndentedString(refundReason)).append("\n");
    sb.append("    exchangeRequestedAt: ").append(toIndentedString(exchangeRequestedAt)).append("\n");
    sb.append("    exchangeCompletedAt: ").append(toIndentedString(exchangeCompletedAt)).append("\n");
    sb.append("    refundRequestedAt: ").append(toIndentedString(refundRequestedAt)).append("\n");
    sb.append("    refundCompletedAt: ").append(toIndentedString(refundCompletedAt)).append("\n");
    sb.append("    refundAmount: ").append(toIndentedString(refundAmount)).append("\n");
    sb.append("    refundTransactionId: ").append(toIndentedString(refundTransactionId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    seatId: ").append(toIndentedString(seatId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    qrCodeImg: ").append(toIndentedString(qrCodeImg)).append("\n");
    sb.append("    originalTicket: ").append(toIndentedString(originalTicket)).append("\n");
    sb.append("    exchangedTicket: ").append(toIndentedString(exchangedTicket)).append("\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

