/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msuser.client.model.ChatSessionDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * ChatMessageDTO
 */
@JsonPropertyOrder({
  ChatMessageDTO.JSON_PROPERTY_ID,
  ChatMessageDTO.JSON_PROPERTY_MESSAGE_TEXT,
  ChatMessageDTO.JSON_PROPERTY_MESSAGE_TYPE,
  ChatMessageDTO.JSON_PROPERTY_TIMESTAMP,
  ChatMessageDTO.JSON_PROPERTY_INTENT,
  ChatMessageDTO.JSON_PROPERTY_ENTITIES,
  ChatMessageDTO.JSON_PROPERTY_CONFIDENCE,
  ChatMessageDTO.JSON_PROPERTY_CREATED_AT,
  ChatMessageDTO.JSON_PROPERTY_UPDATED_AT,
  ChatMessageDTO.JSON_PROPERTY_IS_DELETED,
  ChatMessageDTO.JSON_PROPERTY_DELETED_AT,
  ChatMessageDTO.JSON_PROPERTY_DELETED_BY,
  ChatMessageDTO.JSON_PROPERTY_CHAT_SESSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ChatMessageDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_MESSAGE_TEXT = "messageText";
  @jakarta.annotation.Nonnull
  private String messageText;

  public static final String JSON_PROPERTY_MESSAGE_TYPE = "messageType";
  @jakarta.annotation.Nonnull
  private String messageType;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_INTENT = "intent";
  @jakarta.annotation.Nullable
  private String intent;

  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @jakarta.annotation.Nullable
  private String entities;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @jakarta.annotation.Nullable
  private BigDecimal confidence;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_CHAT_SESSION = "chatSession";
  @jakarta.annotation.Nonnull
  private ChatSessionDTO chatSession;

  public ChatMessageDTO() {
  }

  public ChatMessageDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ChatMessageDTO messageText(@jakarta.annotation.Nonnull String messageText) {
    
    this.messageText = messageText;
    return this;
  }

  /**
   * Get messageText
   * @return messageText
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=1000)
  @JsonProperty(JSON_PROPERTY_MESSAGE_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageText() {
    return messageText;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageText(@jakarta.annotation.Nonnull String messageText) {
    this.messageText = messageText;
  }


  public ChatMessageDTO messageType(@jakarta.annotation.Nonnull String messageType) {
    
    this.messageType = messageType;
    return this;
  }

  /**
   * Get messageType
   * @return messageType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessageType() {
    return messageType;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageType(@jakarta.annotation.Nonnull String messageType) {
    this.messageType = messageType;
  }


  public ChatMessageDTO timestamp(@jakarta.annotation.Nonnull OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public ChatMessageDTO intent(@jakarta.annotation.Nullable String intent) {
    
    this.intent = intent;
    return this;
  }

  /**
   * Get intent
   * @return intent
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=100)
  @JsonProperty(JSON_PROPERTY_INTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIntent() {
    return intent;
  }


  @JsonProperty(JSON_PROPERTY_INTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntent(@jakarta.annotation.Nullable String intent) {
    this.intent = intent;
  }


  public ChatMessageDTO entities(@jakarta.annotation.Nullable String entities) {
    
    this.entities = entities;
    return this;
  }

  /**
   * Get entities
   * @return entities
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=500)
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntities(@jakarta.annotation.Nullable String entities) {
    this.entities = entities;
  }


  public ChatMessageDTO confidence(@jakarta.annotation.Nullable BigDecimal confidence) {
    
    this.confidence = confidence;
    return this;
  }

  /**
   * Get confidence
   * @return confidence
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getConfidence() {
    return confidence;
  }


  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidence(@jakarta.annotation.Nullable BigDecimal confidence) {
    this.confidence = confidence;
  }


  public ChatMessageDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ChatMessageDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ChatMessageDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ChatMessageDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ChatMessageDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public ChatMessageDTO chatSession(@jakarta.annotation.Nonnull ChatSessionDTO chatSession) {
    
    this.chatSession = chatSession;
    return this;
  }

  /**
   * Get chatSession
   * @return chatSession
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CHAT_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatSessionDTO getChatSession() {
    return chatSession;
  }


  @JsonProperty(JSON_PROPERTY_CHAT_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChatSession(@jakarta.annotation.Nonnull ChatSessionDTO chatSession) {
    this.chatSession = chatSession;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatMessageDTO chatMessageDTO = (ChatMessageDTO) o;
    return Objects.equals(this.id, chatMessageDTO.id) &&
        Objects.equals(this.messageText, chatMessageDTO.messageText) &&
        Objects.equals(this.messageType, chatMessageDTO.messageType) &&
        Objects.equals(this.timestamp, chatMessageDTO.timestamp) &&
        Objects.equals(this.intent, chatMessageDTO.intent) &&
        Objects.equals(this.entities, chatMessageDTO.entities) &&
        Objects.equals(this.confidence, chatMessageDTO.confidence) &&
        Objects.equals(this.createdAt, chatMessageDTO.createdAt) &&
        Objects.equals(this.updatedAt, chatMessageDTO.updatedAt) &&
        Objects.equals(this.isDeleted, chatMessageDTO.isDeleted) &&
        Objects.equals(this.deletedAt, chatMessageDTO.deletedAt) &&
        Objects.equals(this.deletedBy, chatMessageDTO.deletedBy) &&
        Objects.equals(this.chatSession, chatMessageDTO.chatSession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, messageText, messageType, timestamp, intent, entities, confidence, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, chatSession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatMessageDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    messageText: ").append(toIndentedString(messageText)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    intent: ").append(toIndentedString(intent)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    chatSession: ").append(toIndentedString(chatSession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

