/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msuser.client.model.AppUserDTO;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TripRecommendationDTO
 */
@JsonPropertyOrder({
  TripRecommendationDTO.JSON_PROPERTY_ID,
  TripRecommendationDTO.JSON_PROPERTY_ORIGIN,
  TripRecommendationDTO.JSON_PROPERTY_DESTINATION,
  TripRecommendationDTO.JSON_PROPERTY_TRAVEL_DATE,
  TripRecommendationDTO.JSON_PROPERTY_PREFERRED_TIME,
  TripRecommendationDTO.JSON_PROPERTY_BUDGET_RANGE,
  TripRecommendationDTO.JSON_PROPERTY_SEAT_PREFERENCE,
  TripRecommendationDTO.JSON_PROPERTY_RECOMMENDED_TRIPS,
  TripRecommendationDTO.JSON_PROPERTY_CONFIDENCE_SCORE,
  TripRecommendationDTO.JSON_PROPERTY_IS_BOOKED,
  TripRecommendationDTO.JSON_PROPERTY_FEEDBACK_RATING,
  TripRecommendationDTO.JSON_PROPERTY_CREATED_AT,
  TripRecommendationDTO.JSON_PROPERTY_UPDATED_AT,
  TripRecommendationDTO.JSON_PROPERTY_IS_DELETED,
  TripRecommendationDTO.JSON_PROPERTY_DELETED_AT,
  TripRecommendationDTO.JSON_PROPERTY_DELETED_BY,
  TripRecommendationDTO.JSON_PROPERTY_USER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TripRecommendationDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_ORIGIN = "origin";
  @jakarta.annotation.Nonnull
  private String origin;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nonnull
  private String destination;

  public static final String JSON_PROPERTY_TRAVEL_DATE = "travelDate";
  @jakarta.annotation.Nonnull
  private LocalDate travelDate;

  public static final String JSON_PROPERTY_PREFERRED_TIME = "preferredTime";
  @jakarta.annotation.Nullable
  private String preferredTime;

  public static final String JSON_PROPERTY_BUDGET_RANGE = "budgetRange";
  @jakarta.annotation.Nullable
  private String budgetRange;

  public static final String JSON_PROPERTY_SEAT_PREFERENCE = "seatPreference";
  @jakarta.annotation.Nullable
  private String seatPreference;

  public static final String JSON_PROPERTY_RECOMMENDED_TRIPS = "recommendedTrips";
  @jakarta.annotation.Nullable
  private String recommendedTrips;

  public static final String JSON_PROPERTY_CONFIDENCE_SCORE = "confidenceScore";
  @jakarta.annotation.Nullable
  private BigDecimal confidenceScore;

  public static final String JSON_PROPERTY_IS_BOOKED = "isBooked";
  @jakarta.annotation.Nullable
  private Boolean isBooked;

  public static final String JSON_PROPERTY_FEEDBACK_RATING = "feedbackRating";
  @jakarta.annotation.Nullable
  private Integer feedbackRating;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_USER = "user";
  @jakarta.annotation.Nonnull
  private AppUserDTO user;

  public TripRecommendationDTO() {
  }

  public TripRecommendationDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TripRecommendationDTO origin(@jakarta.annotation.Nonnull String origin) {
    
    this.origin = origin;
    return this;
  }

  /**
   * Get origin
   * @return origin
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrigin() {
    return origin;
  }


  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrigin(@jakarta.annotation.Nonnull String origin) {
    this.origin = origin;
  }


  public TripRecommendationDTO destination(@jakarta.annotation.Nonnull String destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(@jakarta.annotation.Nonnull String destination) {
    this.destination = destination;
  }


  public TripRecommendationDTO travelDate(@jakarta.annotation.Nonnull LocalDate travelDate) {
    
    this.travelDate = travelDate;
    return this;
  }

  /**
   * Get travelDate
   * @return travelDate
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_TRAVEL_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getTravelDate() {
    return travelDate;
  }


  @JsonProperty(JSON_PROPERTY_TRAVEL_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTravelDate(@jakarta.annotation.Nonnull LocalDate travelDate) {
    this.travelDate = travelDate;
  }


  public TripRecommendationDTO preferredTime(@jakarta.annotation.Nullable String preferredTime) {
    
    this.preferredTime = preferredTime;
    return this;
  }

  /**
   * Get preferredTime
   * @return preferredTime
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PREFERRED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredTime() {
    return preferredTime;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredTime(@jakarta.annotation.Nullable String preferredTime) {
    this.preferredTime = preferredTime;
  }


  public TripRecommendationDTO budgetRange(@jakarta.annotation.Nullable String budgetRange) {
    
    this.budgetRange = budgetRange;
    return this;
  }

  /**
   * Get budgetRange
   * @return budgetRange
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=100)
  @JsonProperty(JSON_PROPERTY_BUDGET_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBudgetRange() {
    return budgetRange;
  }


  @JsonProperty(JSON_PROPERTY_BUDGET_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBudgetRange(@jakarta.annotation.Nullable String budgetRange) {
    this.budgetRange = budgetRange;
  }


  public TripRecommendationDTO seatPreference(@jakarta.annotation.Nullable String seatPreference) {
    
    this.seatPreference = seatPreference;
    return this;
  }

  /**
   * Get seatPreference
   * @return seatPreference
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=50)
  @JsonProperty(JSON_PROPERTY_SEAT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeatPreference() {
    return seatPreference;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatPreference(@jakarta.annotation.Nullable String seatPreference) {
    this.seatPreference = seatPreference;
  }


  public TripRecommendationDTO recommendedTrips(@jakarta.annotation.Nullable String recommendedTrips) {
    
    this.recommendedTrips = recommendedTrips;
    return this;
  }

  /**
   * Get recommendedTrips
   * @return recommendedTrips
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=2000)
  @JsonProperty(JSON_PROPERTY_RECOMMENDED_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRecommendedTrips() {
    return recommendedTrips;
  }


  @JsonProperty(JSON_PROPERTY_RECOMMENDED_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecommendedTrips(@jakarta.annotation.Nullable String recommendedTrips) {
    this.recommendedTrips = recommendedTrips;
  }


  public TripRecommendationDTO confidenceScore(@jakarta.annotation.Nullable BigDecimal confidenceScore) {
    
    this.confidenceScore = confidenceScore;
    return this;
  }

  /**
   * Get confidenceScore
   * @return confidenceScore
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CONFIDENCE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getConfidenceScore() {
    return confidenceScore;
  }


  @JsonProperty(JSON_PROPERTY_CONFIDENCE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidenceScore(@jakarta.annotation.Nullable BigDecimal confidenceScore) {
    this.confidenceScore = confidenceScore;
  }


  public TripRecommendationDTO isBooked(@jakarta.annotation.Nullable Boolean isBooked) {
    
    this.isBooked = isBooked;
    return this;
  }

  /**
   * Get isBooked
   * @return isBooked
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_BOOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsBooked() {
    return isBooked;
  }


  @JsonProperty(JSON_PROPERTY_IS_BOOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsBooked(@jakarta.annotation.Nullable Boolean isBooked) {
    this.isBooked = isBooked;
  }


  public TripRecommendationDTO feedbackRating(@jakarta.annotation.Nullable Integer feedbackRating) {
    
    this.feedbackRating = feedbackRating;
    return this;
  }

  /**
   * Get feedbackRating
   * @return feedbackRating
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FEEDBACK_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFeedbackRating() {
    return feedbackRating;
  }


  @JsonProperty(JSON_PROPERTY_FEEDBACK_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeedbackRating(@jakarta.annotation.Nullable Integer feedbackRating) {
    this.feedbackRating = feedbackRating;
  }


  public TripRecommendationDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TripRecommendationDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TripRecommendationDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TripRecommendationDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TripRecommendationDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public TripRecommendationDTO user(@jakarta.annotation.Nonnull AppUserDTO user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppUserDTO getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUser(@jakarta.annotation.Nonnull AppUserDTO user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripRecommendationDTO tripRecommendationDTO = (TripRecommendationDTO) o;
    return Objects.equals(this.id, tripRecommendationDTO.id) &&
        Objects.equals(this.origin, tripRecommendationDTO.origin) &&
        Objects.equals(this.destination, tripRecommendationDTO.destination) &&
        Objects.equals(this.travelDate, tripRecommendationDTO.travelDate) &&
        Objects.equals(this.preferredTime, tripRecommendationDTO.preferredTime) &&
        Objects.equals(this.budgetRange, tripRecommendationDTO.budgetRange) &&
        Objects.equals(this.seatPreference, tripRecommendationDTO.seatPreference) &&
        Objects.equals(this.recommendedTrips, tripRecommendationDTO.recommendedTrips) &&
        Objects.equals(this.confidenceScore, tripRecommendationDTO.confidenceScore) &&
        Objects.equals(this.isBooked, tripRecommendationDTO.isBooked) &&
        Objects.equals(this.feedbackRating, tripRecommendationDTO.feedbackRating) &&
        Objects.equals(this.createdAt, tripRecommendationDTO.createdAt) &&
        Objects.equals(this.updatedAt, tripRecommendationDTO.updatedAt) &&
        Objects.equals(this.isDeleted, tripRecommendationDTO.isDeleted) &&
        Objects.equals(this.deletedAt, tripRecommendationDTO.deletedAt) &&
        Objects.equals(this.deletedBy, tripRecommendationDTO.deletedBy) &&
        Objects.equals(this.user, tripRecommendationDTO.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, origin, destination, travelDate, preferredTime, budgetRange, seatPreference, recommendedTrips, confidenceScore, isBooked, feedbackRating, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripRecommendationDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    travelDate: ").append(toIndentedString(travelDate)).append("\n");
    sb.append("    preferredTime: ").append(toIndentedString(preferredTime)).append("\n");
    sb.append("    budgetRange: ").append(toIndentedString(budgetRange)).append("\n");
    sb.append("    seatPreference: ").append(toIndentedString(seatPreference)).append("\n");
    sb.append("    recommendedTrips: ").append(toIndentedString(recommendedTrips)).append("\n");
    sb.append("    confidenceScore: ").append(toIndentedString(confidenceScore)).append("\n");
    sb.append("    isBooked: ").append(toIndentedString(isBooked)).append("\n");
    sb.append("    feedbackRating: ").append(toIndentedString(feedbackRating)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

