/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TripStatisticsDTO
 */
@JsonPropertyOrder({
  TripStatisticsDTO.JSON_PROPERTY_ID,
  TripStatisticsDTO.JSON_PROPERTY_ROUTE_ID,
  TripStatisticsDTO.JSON_PROPERTY_VEHICLE_TYPE,
  TripStatisticsDTO.JSON_PROPERTY_OCCASION_TYPE,
  TripStatisticsDTO.JSON_PROPERTY_TOTAL_BOOKINGS,
  TripStatisticsDTO.JSON_PROPERTY_TOTAL_REVENUE,
  TripStatisticsDTO.JSON_PROPERTY_AVERAGE_PRICE,
  TripStatisticsDTO.JSON_PROPERTY_OCCUPANCY_RATE,
  TripStatisticsDTO.JSON_PROPERTY_POPULAR_SEAT_TYPES,
  TripStatisticsDTO.JSON_PROPERTY_PEAK_TRAVEL_TIMES,
  TripStatisticsDTO.JSON_PROPERTY_CANCELLATION_RATE,
  TripStatisticsDTO.JSON_PROPERTY_CUSTOMER_SATISFACTION_SCORE,
  TripStatisticsDTO.JSON_PROPERTY_MONTHLY_TREND,
  TripStatisticsDTO.JSON_PROPERTY_VALID_FROM,
  TripStatisticsDTO.JSON_PROPERTY_VALID_TO,
  TripStatisticsDTO.JSON_PROPERTY_CREATED_AT,
  TripStatisticsDTO.JSON_PROPERTY_UPDATED_AT,
  TripStatisticsDTO.JSON_PROPERTY_IS_DELETED,
  TripStatisticsDTO.JSON_PROPERTY_DELETED_AT,
  TripStatisticsDTO.JSON_PROPERTY_DELETED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TripStatisticsDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_ROUTE_ID = "routeId";
  @jakarta.annotation.Nonnull
  private Long routeId;

  /**
   * Gets or Sets vehicleType
   */
  public enum VehicleTypeEnum {
    STANDARD_BUS_VIP(String.valueOf("STANDARD_BUS_VIP")),
    
    STANDARD_BUS_NORMAL(String.valueOf("STANDARD_BUS_NORMAL")),
    
    LIMOUSINE(String.valueOf("LIMOUSINE"));

    private String value;

    VehicleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VehicleTypeEnum fromValue(String value) {
      for (VehicleTypeEnum b : VehicleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VEHICLE_TYPE = "vehicleType";
  @jakarta.annotation.Nonnull
  private VehicleTypeEnum vehicleType;

  /**
   * Gets or Sets occasionType
   */
  public enum OccasionTypeEnum {
    NORMAL(String.valueOf("NORMAL")),
    
    WEEKEND(String.valueOf("WEEKEND")),
    
    HOLIDAY(String.valueOf("HOLIDAY")),
    
    PEAK(String.valueOf("PEAK")),
    
    OFF_PEAK(String.valueOf("OFF_PEAK")),
    
    TET(String.valueOf("TET"));

    private String value;

    OccasionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OccasionTypeEnum fromValue(String value) {
      for (OccasionTypeEnum b : OccasionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OCCASION_TYPE = "occasionType";
  @jakarta.annotation.Nonnull
  private OccasionTypeEnum occasionType;

  public static final String JSON_PROPERTY_TOTAL_BOOKINGS = "totalBookings";
  @jakarta.annotation.Nullable
  private Integer totalBookings;

  public static final String JSON_PROPERTY_TOTAL_REVENUE = "totalRevenue";
  @jakarta.annotation.Nullable
  private BigDecimal totalRevenue;

  public static final String JSON_PROPERTY_AVERAGE_PRICE = "averagePrice";
  @jakarta.annotation.Nullable
  private BigDecimal averagePrice;

  public static final String JSON_PROPERTY_OCCUPANCY_RATE = "occupancyRate";
  @jakarta.annotation.Nullable
  private BigDecimal occupancyRate;

  public static final String JSON_PROPERTY_POPULAR_SEAT_TYPES = "popularSeatTypes";
  @jakarta.annotation.Nullable
  private String popularSeatTypes;

  public static final String JSON_PROPERTY_PEAK_TRAVEL_TIMES = "peakTravelTimes";
  @jakarta.annotation.Nullable
  private String peakTravelTimes;

  public static final String JSON_PROPERTY_CANCELLATION_RATE = "cancellationRate";
  @jakarta.annotation.Nullable
  private BigDecimal cancellationRate;

  public static final String JSON_PROPERTY_CUSTOMER_SATISFACTION_SCORE = "customerSatisfactionScore";
  @jakarta.annotation.Nullable
  private BigDecimal customerSatisfactionScore;

  public static final String JSON_PROPERTY_MONTHLY_TREND = "monthlyTrend";
  @jakarta.annotation.Nullable
  private String monthlyTrend;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  @jakarta.annotation.Nonnull
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  @jakarta.annotation.Nullable
  private LocalDate validTo;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public TripStatisticsDTO() {
  }

  public TripStatisticsDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TripStatisticsDTO routeId(@jakarta.annotation.Nonnull Long routeId) {
    
    this.routeId = routeId;
    return this;
  }

  /**
   * Get routeId
   * @return routeId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getRouteId() {
    return routeId;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteId(@jakarta.annotation.Nonnull Long routeId) {
    this.routeId = routeId;
  }


  public TripStatisticsDTO vehicleType(@jakarta.annotation.Nonnull VehicleTypeEnum vehicleType) {
    
    this.vehicleType = vehicleType;
    return this;
  }

  /**
   * Get vehicleType
   * @return vehicleType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_VEHICLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VehicleTypeEnum getVehicleType() {
    return vehicleType;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVehicleType(@jakarta.annotation.Nonnull VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
  }


  public TripStatisticsDTO occasionType(@jakarta.annotation.Nonnull OccasionTypeEnum occasionType) {
    
    this.occasionType = occasionType;
    return this;
  }

  /**
   * Get occasionType
   * @return occasionType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OCCASION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OccasionTypeEnum getOccasionType() {
    return occasionType;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionType(@jakarta.annotation.Nonnull OccasionTypeEnum occasionType) {
    this.occasionType = occasionType;
  }


  public TripStatisticsDTO totalBookings(@jakarta.annotation.Nullable Integer totalBookings) {
    
    this.totalBookings = totalBookings;
    return this;
  }

  /**
   * Get totalBookings
   * @return totalBookings
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_BOOKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalBookings() {
    return totalBookings;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_BOOKINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalBookings(@jakarta.annotation.Nullable Integer totalBookings) {
    this.totalBookings = totalBookings;
  }


  public TripStatisticsDTO totalRevenue(@jakarta.annotation.Nullable BigDecimal totalRevenue) {
    
    this.totalRevenue = totalRevenue;
    return this;
  }

  /**
   * Get totalRevenue
   * @return totalRevenue
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TOTAL_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalRevenue() {
    return totalRevenue;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRevenue(@jakarta.annotation.Nullable BigDecimal totalRevenue) {
    this.totalRevenue = totalRevenue;
  }


  public TripStatisticsDTO averagePrice(@jakarta.annotation.Nullable BigDecimal averagePrice) {
    
    this.averagePrice = averagePrice;
    return this;
  }

  /**
   * Get averagePrice
   * @return averagePrice
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_AVERAGE_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAveragePrice() {
    return averagePrice;
  }


  @JsonProperty(JSON_PROPERTY_AVERAGE_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAveragePrice(@jakarta.annotation.Nullable BigDecimal averagePrice) {
    this.averagePrice = averagePrice;
  }


  public TripStatisticsDTO occupancyRate(@jakarta.annotation.Nullable BigDecimal occupancyRate) {
    
    this.occupancyRate = occupancyRate;
    return this;
  }

  /**
   * Get occupancyRate
   * @return occupancyRate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_OCCUPANCY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOccupancyRate() {
    return occupancyRate;
  }


  @JsonProperty(JSON_PROPERTY_OCCUPANCY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOccupancyRate(@jakarta.annotation.Nullable BigDecimal occupancyRate) {
    this.occupancyRate = occupancyRate;
  }


  public TripStatisticsDTO popularSeatTypes(@jakarta.annotation.Nullable String popularSeatTypes) {
    
    this.popularSeatTypes = popularSeatTypes;
    return this;
  }

  /**
   * Get popularSeatTypes
   * @return popularSeatTypes
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_POPULAR_SEAT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPopularSeatTypes() {
    return popularSeatTypes;
  }


  @JsonProperty(JSON_PROPERTY_POPULAR_SEAT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPopularSeatTypes(@jakarta.annotation.Nullable String popularSeatTypes) {
    this.popularSeatTypes = popularSeatTypes;
  }


  public TripStatisticsDTO peakTravelTimes(@jakarta.annotation.Nullable String peakTravelTimes) {
    
    this.peakTravelTimes = peakTravelTimes;
    return this;
  }

  /**
   * Get peakTravelTimes
   * @return peakTravelTimes
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=500)
  @JsonProperty(JSON_PROPERTY_PEAK_TRAVEL_TIMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPeakTravelTimes() {
    return peakTravelTimes;
  }


  @JsonProperty(JSON_PROPERTY_PEAK_TRAVEL_TIMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeakTravelTimes(@jakarta.annotation.Nullable String peakTravelTimes) {
    this.peakTravelTimes = peakTravelTimes;
  }


  public TripStatisticsDTO cancellationRate(@jakarta.annotation.Nullable BigDecimal cancellationRate) {
    
    this.cancellationRate = cancellationRate;
    return this;
  }

  /**
   * Get cancellationRate
   * @return cancellationRate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CANCELLATION_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCancellationRate() {
    return cancellationRate;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLATION_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancellationRate(@jakarta.annotation.Nullable BigDecimal cancellationRate) {
    this.cancellationRate = cancellationRate;
  }


  public TripStatisticsDTO customerSatisfactionScore(@jakarta.annotation.Nullable BigDecimal customerSatisfactionScore) {
    
    this.customerSatisfactionScore = customerSatisfactionScore;
    return this;
  }

  /**
   * Get customerSatisfactionScore
   * @return customerSatisfactionScore
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CUSTOMER_SATISFACTION_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCustomerSatisfactionScore() {
    return customerSatisfactionScore;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_SATISFACTION_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerSatisfactionScore(@jakarta.annotation.Nullable BigDecimal customerSatisfactionScore) {
    this.customerSatisfactionScore = customerSatisfactionScore;
  }


  public TripStatisticsDTO monthlyTrend(@jakarta.annotation.Nullable String monthlyTrend) {
    
    this.monthlyTrend = monthlyTrend;
    return this;
  }

  /**
   * Get monthlyTrend
   * @return monthlyTrend
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=1000)
  @JsonProperty(JSON_PROPERTY_MONTHLY_TREND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMonthlyTrend() {
    return monthlyTrend;
  }


  @JsonProperty(JSON_PROPERTY_MONTHLY_TREND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonthlyTrend(@jakarta.annotation.Nullable String monthlyTrend) {
    this.monthlyTrend = monthlyTrend;
  }


  public TripStatisticsDTO validFrom(@jakarta.annotation.Nonnull LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

  /**
   * Get validFrom
   * @return validFrom
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(@jakarta.annotation.Nonnull LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public TripStatisticsDTO validTo(@jakarta.annotation.Nullable LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

  /**
   * Get validTo
   * @return validTo
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(@jakarta.annotation.Nullable LocalDate validTo) {
    this.validTo = validTo;
  }


  public TripStatisticsDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TripStatisticsDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TripStatisticsDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TripStatisticsDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TripStatisticsDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripStatisticsDTO tripStatisticsDTO = (TripStatisticsDTO) o;
    return Objects.equals(this.id, tripStatisticsDTO.id) &&
        Objects.equals(this.routeId, tripStatisticsDTO.routeId) &&
        Objects.equals(this.vehicleType, tripStatisticsDTO.vehicleType) &&
        Objects.equals(this.occasionType, tripStatisticsDTO.occasionType) &&
        Objects.equals(this.totalBookings, tripStatisticsDTO.totalBookings) &&
        Objects.equals(this.totalRevenue, tripStatisticsDTO.totalRevenue) &&
        Objects.equals(this.averagePrice, tripStatisticsDTO.averagePrice) &&
        Objects.equals(this.occupancyRate, tripStatisticsDTO.occupancyRate) &&
        Objects.equals(this.popularSeatTypes, tripStatisticsDTO.popularSeatTypes) &&
        Objects.equals(this.peakTravelTimes, tripStatisticsDTO.peakTravelTimes) &&
        Objects.equals(this.cancellationRate, tripStatisticsDTO.cancellationRate) &&
        Objects.equals(this.customerSatisfactionScore, tripStatisticsDTO.customerSatisfactionScore) &&
        Objects.equals(this.monthlyTrend, tripStatisticsDTO.monthlyTrend) &&
        Objects.equals(this.validFrom, tripStatisticsDTO.validFrom) &&
        Objects.equals(this.validTo, tripStatisticsDTO.validTo) &&
        Objects.equals(this.createdAt, tripStatisticsDTO.createdAt) &&
        Objects.equals(this.updatedAt, tripStatisticsDTO.updatedAt) &&
        Objects.equals(this.isDeleted, tripStatisticsDTO.isDeleted) &&
        Objects.equals(this.deletedAt, tripStatisticsDTO.deletedAt) &&
        Objects.equals(this.deletedBy, tripStatisticsDTO.deletedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, routeId, vehicleType, occasionType, totalBookings, totalRevenue, averagePrice, occupancyRate, popularSeatTypes, peakTravelTimes, cancellationRate, customerSatisfactionScore, monthlyTrend, validFrom, validTo, createdAt, updatedAt, isDeleted, deletedAt, deletedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripStatisticsDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("    occasionType: ").append(toIndentedString(occasionType)).append("\n");
    sb.append("    totalBookings: ").append(toIndentedString(totalBookings)).append("\n");
    sb.append("    totalRevenue: ").append(toIndentedString(totalRevenue)).append("\n");
    sb.append("    averagePrice: ").append(toIndentedString(averagePrice)).append("\n");
    sb.append("    occupancyRate: ").append(toIndentedString(occupancyRate)).append("\n");
    sb.append("    popularSeatTypes: ").append(toIndentedString(popularSeatTypes)).append("\n");
    sb.append("    peakTravelTimes: ").append(toIndentedString(peakTravelTimes)).append("\n");
    sb.append("    cancellationRate: ").append(toIndentedString(cancellationRate)).append("\n");
    sb.append("    customerSatisfactionScore: ").append(toIndentedString(customerSatisfactionScore)).append("\n");
    sb.append("    monthlyTrend: ").append(toIndentedString(monthlyTrend)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

