/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msuser.client.model.ChatSessionDTO;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserQueryDTO
 */
@JsonPropertyOrder({
  UserQueryDTO.JSON_PROPERTY_ID,
  UserQueryDTO.JSON_PROPERTY_QUERY_TEXT,
  UserQueryDTO.JSON_PROPERTY_QUERY_TYPE,
  UserQueryDTO.JSON_PROPERTY_PARAMETERS,
  UserQueryDTO.JSON_PROPERTY_RESPONSE_GENERATED,
  UserQueryDTO.JSON_PROPERTY_RESPONSE_TIME,
  UserQueryDTO.JSON_PROPERTY_CREATED_AT,
  UserQueryDTO.JSON_PROPERTY_UPDATED_AT,
  UserQueryDTO.JSON_PROPERTY_IS_DELETED,
  UserQueryDTO.JSON_PROPERTY_DELETED_AT,
  UserQueryDTO.JSON_PROPERTY_DELETED_BY,
  UserQueryDTO.JSON_PROPERTY_CHAT_SESSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UserQueryDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_QUERY_TEXT = "queryText";
  @jakarta.annotation.Nonnull
  private String queryText;

  public static final String JSON_PROPERTY_QUERY_TYPE = "queryType";
  @jakarta.annotation.Nonnull
  private String queryType;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @jakarta.annotation.Nullable
  private String parameters;

  public static final String JSON_PROPERTY_RESPONSE_GENERATED = "responseGenerated";
  @jakarta.annotation.Nullable
  private Boolean responseGenerated;

  public static final String JSON_PROPERTY_RESPONSE_TIME = "responseTime";
  @jakarta.annotation.Nullable
  private Integer responseTime;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_CHAT_SESSION = "chatSession";
  @jakarta.annotation.Nonnull
  private ChatSessionDTO chatSession;

  public UserQueryDTO() {
  }

  public UserQueryDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public UserQueryDTO queryText(@jakarta.annotation.Nonnull String queryText) {
    
    this.queryText = queryText;
    return this;
  }

  /**
   * Get queryText
   * @return queryText
   */
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=1000)
  @JsonProperty(JSON_PROPERTY_QUERY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQueryText() {
    return queryText;
  }


  @JsonProperty(JSON_PROPERTY_QUERY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueryText(@jakarta.annotation.Nonnull String queryText) {
    this.queryText = queryText;
  }


  public UserQueryDTO queryType(@jakarta.annotation.Nonnull String queryType) {
    
    this.queryType = queryType;
    return this;
  }

  /**
   * Get queryType
   * @return queryType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_QUERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQueryType() {
    return queryType;
  }


  @JsonProperty(JSON_PROPERTY_QUERY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueryType(@jakarta.annotation.Nonnull String queryType) {
    this.queryType = queryType;
  }


  public UserQueryDTO parameters(@jakarta.annotation.Nullable String parameters) {
    
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=1000)
  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParameters() {
    return parameters;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameters(@jakarta.annotation.Nullable String parameters) {
    this.parameters = parameters;
  }


  public UserQueryDTO responseGenerated(@jakarta.annotation.Nullable Boolean responseGenerated) {
    
    this.responseGenerated = responseGenerated;
    return this;
  }

  /**
   * Get responseGenerated
   * @return responseGenerated
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESPONSE_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getResponseGenerated() {
    return responseGenerated;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_GENERATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseGenerated(@jakarta.annotation.Nullable Boolean responseGenerated) {
    this.responseGenerated = responseGenerated;
  }


  public UserQueryDTO responseTime(@jakarta.annotation.Nullable Integer responseTime) {
    
    this.responseTime = responseTime;
    return this;
  }

  /**
   * Get responseTime
   * @return responseTime
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESPONSE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResponseTime() {
    return responseTime;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseTime(@jakarta.annotation.Nullable Integer responseTime) {
    this.responseTime = responseTime;
  }


  public UserQueryDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public UserQueryDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public UserQueryDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public UserQueryDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public UserQueryDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public UserQueryDTO chatSession(@jakarta.annotation.Nonnull ChatSessionDTO chatSession) {
    
    this.chatSession = chatSession;
    return this;
  }

  /**
   * Get chatSession
   * @return chatSession
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CHAT_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatSessionDTO getChatSession() {
    return chatSession;
  }


  @JsonProperty(JSON_PROPERTY_CHAT_SESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChatSession(@jakarta.annotation.Nonnull ChatSessionDTO chatSession) {
    this.chatSession = chatSession;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserQueryDTO userQueryDTO = (UserQueryDTO) o;
    return Objects.equals(this.id, userQueryDTO.id) &&
        Objects.equals(this.queryText, userQueryDTO.queryText) &&
        Objects.equals(this.queryType, userQueryDTO.queryType) &&
        Objects.equals(this.parameters, userQueryDTO.parameters) &&
        Objects.equals(this.responseGenerated, userQueryDTO.responseGenerated) &&
        Objects.equals(this.responseTime, userQueryDTO.responseTime) &&
        Objects.equals(this.createdAt, userQueryDTO.createdAt) &&
        Objects.equals(this.updatedAt, userQueryDTO.updatedAt) &&
        Objects.equals(this.isDeleted, userQueryDTO.isDeleted) &&
        Objects.equals(this.deletedAt, userQueryDTO.deletedAt) &&
        Objects.equals(this.deletedBy, userQueryDTO.deletedBy) &&
        Objects.equals(this.chatSession, userQueryDTO.chatSession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, queryText, queryType, parameters, responseGenerated, responseTime, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, chatSession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserQueryDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    queryText: ").append(toIndentedString(queryText)).append("\n");
    sb.append("    queryType: ").append(toIndentedString(queryType)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    responseGenerated: ").append(toIndentedString(responseGenerated)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    chatSession: ").append(toIndentedString(chatSession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

