/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserStatisticsDTO
 */
@JsonPropertyOrder({
  UserStatisticsDTO.JSON_PROPERTY_ID,
  UserStatisticsDTO.JSON_PROPERTY_TOTAL_TRIPS,
  UserStatisticsDTO.JSON_PROPERTY_TOTAL_SPENT,
  UserStatisticsDTO.JSON_PROPERTY_FAVORITE_ROUTES,
  UserStatisticsDTO.JSON_PROPERTY_PREFERRED_VEHICLE_TYPES,
  UserStatisticsDTO.JSON_PROPERTY_AVERAGE_TRIP_DURATION,
  UserStatisticsDTO.JSON_PROPERTY_LAST_TRAVEL_DATE,
  UserStatisticsDTO.JSON_PROPERTY_BOOKING_FREQUENCY,
  UserStatisticsDTO.JSON_PROPERTY_LOYALTY_POINTS,
  UserStatisticsDTO.JSON_PROPERTY_MOST_FREQUENT_ORIGIN,
  UserStatisticsDTO.JSON_PROPERTY_MOST_FREQUENT_DESTINATION,
  UserStatisticsDTO.JSON_PROPERTY_AVERAGE_TRIP_DISTANCE,
  UserStatisticsDTO.JSON_PROPERTY_PEAK_TRAVEL_TIME,
  UserStatisticsDTO.JSON_PROPERTY_WEEKEND_TRIPS,
  UserStatisticsDTO.JSON_PROPERTY_HOLIDAY_TRIPS,
  UserStatisticsDTO.JSON_PROPERTY_CANCELLED_TRIPS,
  UserStatisticsDTO.JSON_PROPERTY_ON_TIME_PERFORMANCE_RATE,
  UserStatisticsDTO.JSON_PROPERTY_PREFERRED_SEAT_TYPES,
  UserStatisticsDTO.JSON_PROPERTY_MONTHLY_TRIP_COUNT,
  UserStatisticsDTO.JSON_PROPERTY_CREATED_AT,
  UserStatisticsDTO.JSON_PROPERTY_UPDATED_AT,
  UserStatisticsDTO.JSON_PROPERTY_IS_DELETED,
  UserStatisticsDTO.JSON_PROPERTY_DELETED_AT,
  UserStatisticsDTO.JSON_PROPERTY_DELETED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UserStatisticsDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_TOTAL_TRIPS = "totalTrips";
  @jakarta.annotation.Nullable
  private Integer totalTrips;

  public static final String JSON_PROPERTY_TOTAL_SPENT = "totalSpent";
  @jakarta.annotation.Nullable
  private BigDecimal totalSpent;

  public static final String JSON_PROPERTY_FAVORITE_ROUTES = "favoriteRoutes";
  @jakarta.annotation.Nullable
  private String favoriteRoutes;

  public static final String JSON_PROPERTY_PREFERRED_VEHICLE_TYPES = "preferredVehicleTypes";
  @jakarta.annotation.Nullable
  private String preferredVehicleTypes;

  public static final String JSON_PROPERTY_AVERAGE_TRIP_DURATION = "averageTripDuration";
  @jakarta.annotation.Nullable
  private Integer averageTripDuration;

  public static final String JSON_PROPERTY_LAST_TRAVEL_DATE = "lastTravelDate";
  @jakarta.annotation.Nullable
  private LocalDate lastTravelDate;

  public static final String JSON_PROPERTY_BOOKING_FREQUENCY = "bookingFrequency";
  @jakarta.annotation.Nullable
  private String bookingFrequency;

  public static final String JSON_PROPERTY_LOYALTY_POINTS = "loyaltyPoints";
  @jakarta.annotation.Nullable
  private Integer loyaltyPoints;

  public static final String JSON_PROPERTY_MOST_FREQUENT_ORIGIN = "mostFrequentOrigin";
  @jakarta.annotation.Nullable
  private String mostFrequentOrigin;

  public static final String JSON_PROPERTY_MOST_FREQUENT_DESTINATION = "mostFrequentDestination";
  @jakarta.annotation.Nullable
  private String mostFrequentDestination;

  public static final String JSON_PROPERTY_AVERAGE_TRIP_DISTANCE = "averageTripDistance";
  @jakarta.annotation.Nullable
  private BigDecimal averageTripDistance;

  public static final String JSON_PROPERTY_PEAK_TRAVEL_TIME = "peakTravelTime";
  @jakarta.annotation.Nullable
  private String peakTravelTime;

  public static final String JSON_PROPERTY_WEEKEND_TRIPS = "weekendTrips";
  @jakarta.annotation.Nullable
  private Integer weekendTrips;

  public static final String JSON_PROPERTY_HOLIDAY_TRIPS = "holidayTrips";
  @jakarta.annotation.Nullable
  private Integer holidayTrips;

  public static final String JSON_PROPERTY_CANCELLED_TRIPS = "cancelledTrips";
  @jakarta.annotation.Nullable
  private Integer cancelledTrips;

  public static final String JSON_PROPERTY_ON_TIME_PERFORMANCE_RATE = "onTimePerformanceRate";
  @jakarta.annotation.Nullable
  private BigDecimal onTimePerformanceRate;

  public static final String JSON_PROPERTY_PREFERRED_SEAT_TYPES = "preferredSeatTypes";
  @jakarta.annotation.Nullable
  private String preferredSeatTypes;

  public static final String JSON_PROPERTY_MONTHLY_TRIP_COUNT = "monthlyTripCount";
  @jakarta.annotation.Nullable
  private Integer monthlyTripCount;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public UserStatisticsDTO() {
  }

  public UserStatisticsDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public UserStatisticsDTO totalTrips(@jakarta.annotation.Nullable Integer totalTrips) {
    
    this.totalTrips = totalTrips;
    return this;
  }

  /**
   * Get totalTrips
   * @return totalTrips
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalTrips() {
    return totalTrips;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTrips(@jakarta.annotation.Nullable Integer totalTrips) {
    this.totalTrips = totalTrips;
  }


  public UserStatisticsDTO totalSpent(@jakarta.annotation.Nullable BigDecimal totalSpent) {
    
    this.totalSpent = totalSpent;
    return this;
  }

  /**
   * Get totalSpent
   * @return totalSpent
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TOTAL_SPENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalSpent() {
    return totalSpent;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_SPENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalSpent(@jakarta.annotation.Nullable BigDecimal totalSpent) {
    this.totalSpent = totalSpent;
  }


  public UserStatisticsDTO favoriteRoutes(@jakarta.annotation.Nullable String favoriteRoutes) {
    
    this.favoriteRoutes = favoriteRoutes;
    return this;
  }

  /**
   * Get favoriteRoutes
   * @return favoriteRoutes
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=1000)
  @JsonProperty(JSON_PROPERTY_FAVORITE_ROUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFavoriteRoutes() {
    return favoriteRoutes;
  }


  @JsonProperty(JSON_PROPERTY_FAVORITE_ROUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFavoriteRoutes(@jakarta.annotation.Nullable String favoriteRoutes) {
    this.favoriteRoutes = favoriteRoutes;
  }


  public UserStatisticsDTO preferredVehicleTypes(@jakarta.annotation.Nullable String preferredVehicleTypes) {
    
    this.preferredVehicleTypes = preferredVehicleTypes;
    return this;
  }

  /**
   * Get preferredVehicleTypes
   * @return preferredVehicleTypes
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_PREFERRED_VEHICLE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredVehicleTypes() {
    return preferredVehicleTypes;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_VEHICLE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredVehicleTypes(@jakarta.annotation.Nullable String preferredVehicleTypes) {
    this.preferredVehicleTypes = preferredVehicleTypes;
  }


  public UserStatisticsDTO averageTripDuration(@jakarta.annotation.Nullable Integer averageTripDuration) {
    
    this.averageTripDuration = averageTripDuration;
    return this;
  }

  /**
   * Get averageTripDuration
   * @return averageTripDuration
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AVERAGE_TRIP_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAverageTripDuration() {
    return averageTripDuration;
  }


  @JsonProperty(JSON_PROPERTY_AVERAGE_TRIP_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageTripDuration(@jakarta.annotation.Nullable Integer averageTripDuration) {
    this.averageTripDuration = averageTripDuration;
  }


  public UserStatisticsDTO lastTravelDate(@jakarta.annotation.Nullable LocalDate lastTravelDate) {
    
    this.lastTravelDate = lastTravelDate;
    return this;
  }

  /**
   * Get lastTravelDate
   * @return lastTravelDate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_LAST_TRAVEL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getLastTravelDate() {
    return lastTravelDate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_TRAVEL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastTravelDate(@jakarta.annotation.Nullable LocalDate lastTravelDate) {
    this.lastTravelDate = lastTravelDate;
  }


  public UserStatisticsDTO bookingFrequency(@jakarta.annotation.Nullable String bookingFrequency) {
    
    this.bookingFrequency = bookingFrequency;
    return this;
  }

  /**
   * Get bookingFrequency
   * @return bookingFrequency
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=50)
  @JsonProperty(JSON_PROPERTY_BOOKING_FREQUENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBookingFrequency() {
    return bookingFrequency;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_FREQUENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingFrequency(@jakarta.annotation.Nullable String bookingFrequency) {
    this.bookingFrequency = bookingFrequency;
  }


  public UserStatisticsDTO loyaltyPoints(@jakarta.annotation.Nullable Integer loyaltyPoints) {
    
    this.loyaltyPoints = loyaltyPoints;
    return this;
  }

  /**
   * Get loyaltyPoints
   * @return loyaltyPoints
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LOYALTY_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoyaltyPoints() {
    return loyaltyPoints;
  }


  @JsonProperty(JSON_PROPERTY_LOYALTY_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoyaltyPoints(@jakarta.annotation.Nullable Integer loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
  }


  public UserStatisticsDTO mostFrequentOrigin(@jakarta.annotation.Nullable String mostFrequentOrigin) {
    
    this.mostFrequentOrigin = mostFrequentOrigin;
    return this;
  }

  /**
   * Get mostFrequentOrigin
   * @return mostFrequentOrigin
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_MOST_FREQUENT_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMostFrequentOrigin() {
    return mostFrequentOrigin;
  }


  @JsonProperty(JSON_PROPERTY_MOST_FREQUENT_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMostFrequentOrigin(@jakarta.annotation.Nullable String mostFrequentOrigin) {
    this.mostFrequentOrigin = mostFrequentOrigin;
  }


  public UserStatisticsDTO mostFrequentDestination(@jakarta.annotation.Nullable String mostFrequentDestination) {
    
    this.mostFrequentDestination = mostFrequentDestination;
    return this;
  }

  /**
   * Get mostFrequentDestination
   * @return mostFrequentDestination
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_MOST_FREQUENT_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMostFrequentDestination() {
    return mostFrequentDestination;
  }


  @JsonProperty(JSON_PROPERTY_MOST_FREQUENT_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMostFrequentDestination(@jakarta.annotation.Nullable String mostFrequentDestination) {
    this.mostFrequentDestination = mostFrequentDestination;
  }


  public UserStatisticsDTO averageTripDistance(@jakarta.annotation.Nullable BigDecimal averageTripDistance) {
    
    this.averageTripDistance = averageTripDistance;
    return this;
  }

  /**
   * Get averageTripDistance
   * @return averageTripDistance
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_AVERAGE_TRIP_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAverageTripDistance() {
    return averageTripDistance;
  }


  @JsonProperty(JSON_PROPERTY_AVERAGE_TRIP_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageTripDistance(@jakarta.annotation.Nullable BigDecimal averageTripDistance) {
    this.averageTripDistance = averageTripDistance;
  }


  public UserStatisticsDTO peakTravelTime(@jakarta.annotation.Nullable String peakTravelTime) {
    
    this.peakTravelTime = peakTravelTime;
    return this;
  }

  /**
   * Get peakTravelTime
   * @return peakTravelTime
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=50)
  @JsonProperty(JSON_PROPERTY_PEAK_TRAVEL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPeakTravelTime() {
    return peakTravelTime;
  }


  @JsonProperty(JSON_PROPERTY_PEAK_TRAVEL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeakTravelTime(@jakarta.annotation.Nullable String peakTravelTime) {
    this.peakTravelTime = peakTravelTime;
  }


  public UserStatisticsDTO weekendTrips(@jakarta.annotation.Nullable Integer weekendTrips) {
    
    this.weekendTrips = weekendTrips;
    return this;
  }

  /**
   * Get weekendTrips
   * @return weekendTrips
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_WEEKEND_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeekendTrips() {
    return weekendTrips;
  }


  @JsonProperty(JSON_PROPERTY_WEEKEND_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeekendTrips(@jakarta.annotation.Nullable Integer weekendTrips) {
    this.weekendTrips = weekendTrips;
  }


  public UserStatisticsDTO holidayTrips(@jakarta.annotation.Nullable Integer holidayTrips) {
    
    this.holidayTrips = holidayTrips;
    return this;
  }

  /**
   * Get holidayTrips
   * @return holidayTrips
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_HOLIDAY_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHolidayTrips() {
    return holidayTrips;
  }


  @JsonProperty(JSON_PROPERTY_HOLIDAY_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHolidayTrips(@jakarta.annotation.Nullable Integer holidayTrips) {
    this.holidayTrips = holidayTrips;
  }


  public UserStatisticsDTO cancelledTrips(@jakarta.annotation.Nullable Integer cancelledTrips) {
    
    this.cancelledTrips = cancelledTrips;
    return this;
  }

  /**
   * Get cancelledTrips
   * @return cancelledTrips
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CANCELLED_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCancelledTrips() {
    return cancelledTrips;
  }


  @JsonProperty(JSON_PROPERTY_CANCELLED_TRIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCancelledTrips(@jakarta.annotation.Nullable Integer cancelledTrips) {
    this.cancelledTrips = cancelledTrips;
  }


  public UserStatisticsDTO onTimePerformanceRate(@jakarta.annotation.Nullable BigDecimal onTimePerformanceRate) {
    
    this.onTimePerformanceRate = onTimePerformanceRate;
    return this;
  }

  /**
   * Get onTimePerformanceRate
   * @return onTimePerformanceRate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_ON_TIME_PERFORMANCE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOnTimePerformanceRate() {
    return onTimePerformanceRate;
  }


  @JsonProperty(JSON_PROPERTY_ON_TIME_PERFORMANCE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOnTimePerformanceRate(@jakarta.annotation.Nullable BigDecimal onTimePerformanceRate) {
    this.onTimePerformanceRate = onTimePerformanceRate;
  }


  public UserStatisticsDTO preferredSeatTypes(@jakarta.annotation.Nullable String preferredSeatTypes) {
    
    this.preferredSeatTypes = preferredSeatTypes;
    return this;
  }

  /**
   * Get preferredSeatTypes
   * @return preferredSeatTypes
   */
  @jakarta.annotation.Nullable
 @Size(min=0,max=200)
  @JsonProperty(JSON_PROPERTY_PREFERRED_SEAT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredSeatTypes() {
    return preferredSeatTypes;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_SEAT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredSeatTypes(@jakarta.annotation.Nullable String preferredSeatTypes) {
    this.preferredSeatTypes = preferredSeatTypes;
  }


  public UserStatisticsDTO monthlyTripCount(@jakarta.annotation.Nullable Integer monthlyTripCount) {
    
    this.monthlyTripCount = monthlyTripCount;
    return this;
  }

  /**
   * Get monthlyTripCount
   * @return monthlyTripCount
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MONTHLY_TRIP_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMonthlyTripCount() {
    return monthlyTripCount;
  }


  @JsonProperty(JSON_PROPERTY_MONTHLY_TRIP_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonthlyTripCount(@jakarta.annotation.Nullable Integer monthlyTripCount) {
    this.monthlyTripCount = monthlyTripCount;
  }


  public UserStatisticsDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public UserStatisticsDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public UserStatisticsDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public UserStatisticsDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public UserStatisticsDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserStatisticsDTO userStatisticsDTO = (UserStatisticsDTO) o;
    return Objects.equals(this.id, userStatisticsDTO.id) &&
        Objects.equals(this.totalTrips, userStatisticsDTO.totalTrips) &&
        Objects.equals(this.totalSpent, userStatisticsDTO.totalSpent) &&
        Objects.equals(this.favoriteRoutes, userStatisticsDTO.favoriteRoutes) &&
        Objects.equals(this.preferredVehicleTypes, userStatisticsDTO.preferredVehicleTypes) &&
        Objects.equals(this.averageTripDuration, userStatisticsDTO.averageTripDuration) &&
        Objects.equals(this.lastTravelDate, userStatisticsDTO.lastTravelDate) &&
        Objects.equals(this.bookingFrequency, userStatisticsDTO.bookingFrequency) &&
        Objects.equals(this.loyaltyPoints, userStatisticsDTO.loyaltyPoints) &&
        Objects.equals(this.mostFrequentOrigin, userStatisticsDTO.mostFrequentOrigin) &&
        Objects.equals(this.mostFrequentDestination, userStatisticsDTO.mostFrequentDestination) &&
        Objects.equals(this.averageTripDistance, userStatisticsDTO.averageTripDistance) &&
        Objects.equals(this.peakTravelTime, userStatisticsDTO.peakTravelTime) &&
        Objects.equals(this.weekendTrips, userStatisticsDTO.weekendTrips) &&
        Objects.equals(this.holidayTrips, userStatisticsDTO.holidayTrips) &&
        Objects.equals(this.cancelledTrips, userStatisticsDTO.cancelledTrips) &&
        Objects.equals(this.onTimePerformanceRate, userStatisticsDTO.onTimePerformanceRate) &&
        Objects.equals(this.preferredSeatTypes, userStatisticsDTO.preferredSeatTypes) &&
        Objects.equals(this.monthlyTripCount, userStatisticsDTO.monthlyTripCount) &&
        Objects.equals(this.createdAt, userStatisticsDTO.createdAt) &&
        Objects.equals(this.updatedAt, userStatisticsDTO.updatedAt) &&
        Objects.equals(this.isDeleted, userStatisticsDTO.isDeleted) &&
        Objects.equals(this.deletedAt, userStatisticsDTO.deletedAt) &&
        Objects.equals(this.deletedBy, userStatisticsDTO.deletedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, totalTrips, totalSpent, favoriteRoutes, preferredVehicleTypes, averageTripDuration, lastTravelDate, bookingFrequency, loyaltyPoints, mostFrequentOrigin, mostFrequentDestination, averageTripDistance, peakTravelTime, weekendTrips, holidayTrips, cancelledTrips, onTimePerformanceRate, preferredSeatTypes, monthlyTripCount, createdAt, updatedAt, isDeleted, deletedAt, deletedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserStatisticsDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    totalTrips: ").append(toIndentedString(totalTrips)).append("\n");
    sb.append("    totalSpent: ").append(toIndentedString(totalSpent)).append("\n");
    sb.append("    favoriteRoutes: ").append(toIndentedString(favoriteRoutes)).append("\n");
    sb.append("    preferredVehicleTypes: ").append(toIndentedString(preferredVehicleTypes)).append("\n");
    sb.append("    averageTripDuration: ").append(toIndentedString(averageTripDuration)).append("\n");
    sb.append("    lastTravelDate: ").append(toIndentedString(lastTravelDate)).append("\n");
    sb.append("    bookingFrequency: ").append(toIndentedString(bookingFrequency)).append("\n");
    sb.append("    loyaltyPoints: ").append(toIndentedString(loyaltyPoints)).append("\n");
    sb.append("    mostFrequentOrigin: ").append(toIndentedString(mostFrequentOrigin)).append("\n");
    sb.append("    mostFrequentDestination: ").append(toIndentedString(mostFrequentDestination)).append("\n");
    sb.append("    averageTripDistance: ").append(toIndentedString(averageTripDistance)).append("\n");
    sb.append("    peakTravelTime: ").append(toIndentedString(peakTravelTime)).append("\n");
    sb.append("    weekendTrips: ").append(toIndentedString(weekendTrips)).append("\n");
    sb.append("    holidayTrips: ").append(toIndentedString(holidayTrips)).append("\n");
    sb.append("    cancelledTrips: ").append(toIndentedString(cancelledTrips)).append("\n");
    sb.append("    onTimePerformanceRate: ").append(toIndentedString(onTimePerformanceRate)).append("\n");
    sb.append("    preferredSeatTypes: ").append(toIndentedString(preferredSeatTypes)).append("\n");
    sb.append("    monthlyTripCount: ").append(toIndentedString(monthlyTripCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

