/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * AttachBookingRequestDTO
 */
@JsonPropertyOrder({
  AttachBookingRequestDTO.JSON_PROPERTY_LOCK_GROUP_ID,
  AttachBookingRequestDTO.JSON_PROPERTY_BOOKING_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AttachBookingRequestDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LOCK_GROUP_ID = "lockGroupId";
  @jakarta.annotation.Nullable
  private String lockGroupId;

  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nonnull
  private Long bookingId;

  public AttachBookingRequestDTO() {
  }

  public AttachBookingRequestDTO lockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    
    this.lockGroupId = lockGroupId;
    return this;
  }

  /**
   * Get lockGroupId
   * @return lockGroupId
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLockGroupId() {
    return lockGroupId;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    this.lockGroupId = lockGroupId;
  }


  public AttachBookingRequestDTO bookingId(@jakarta.annotation.Nonnull Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingId(@jakarta.annotation.Nonnull Long bookingId) {
    this.bookingId = bookingId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachBookingRequestDTO attachBookingRequestDTO = (AttachBookingRequestDTO) o;
    return Objects.equals(this.lockGroupId, attachBookingRequestDTO.lockGroupId) &&
        Objects.equals(this.bookingId, attachBookingRequestDTO.bookingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lockGroupId, bookingId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachBookingRequestDTO {\n");
    sb.append("    lockGroupId: ").append(toIndentedString(lockGroupId)).append("\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

