/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * AutoScheduleResponse
 */
@JsonPropertyOrder({
  AutoScheduleResponse.JSON_PROPERTY_SUCCESS,
  AutoScheduleResponse.JSON_PROPERTY_MESSAGE,
  AutoScheduleResponse.JSON_PROPERTY_SCHEDULES_PROCESSED,
  AutoScheduleResponse.JSON_PROPERTY_TRIPS_CREATED,
  AutoScheduleResponse.JSON_PROPERTY_TRIPS_BY_SCHEDULE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AutoScheduleResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUCCESS = "success";
  @jakarta.annotation.Nullable
  private Boolean success;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_SCHEDULES_PROCESSED = "schedulesProcessed";
  @jakarta.annotation.Nullable
  private Integer schedulesProcessed;

  public static final String JSON_PROPERTY_TRIPS_CREATED = "tripsCreated";
  @jakarta.annotation.Nullable
  private Integer tripsCreated;

  public static final String JSON_PROPERTY_TRIPS_BY_SCHEDULE = "tripsBySchedule";
  @jakarta.annotation.Nullable
  private Map<String, Integer> tripsBySchedule = new HashMap<>();

  public AutoScheduleResponse() {
  }

  public AutoScheduleResponse success(@jakarta.annotation.Nullable Boolean success) {
    
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@jakarta.annotation.Nullable Boolean success) {
    this.success = success;
  }


  public AutoScheduleResponse message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public AutoScheduleResponse schedulesProcessed(@jakarta.annotation.Nullable Integer schedulesProcessed) {
    
    this.schedulesProcessed = schedulesProcessed;
    return this;
  }

  /**
   * Get schedulesProcessed
   * @return schedulesProcessed
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SCHEDULES_PROCESSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSchedulesProcessed() {
    return schedulesProcessed;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULES_PROCESSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedulesProcessed(@jakarta.annotation.Nullable Integer schedulesProcessed) {
    this.schedulesProcessed = schedulesProcessed;
  }


  public AutoScheduleResponse tripsCreated(@jakarta.annotation.Nullable Integer tripsCreated) {
    
    this.tripsCreated = tripsCreated;
    return this;
  }

  /**
   * Get tripsCreated
   * @return tripsCreated
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TRIPS_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTripsCreated() {
    return tripsCreated;
  }


  @JsonProperty(JSON_PROPERTY_TRIPS_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTripsCreated(@jakarta.annotation.Nullable Integer tripsCreated) {
    this.tripsCreated = tripsCreated;
  }


  public AutoScheduleResponse tripsBySchedule(@jakarta.annotation.Nullable Map<String, Integer> tripsBySchedule) {
    
    this.tripsBySchedule = tripsBySchedule;
    return this;
  }

  public AutoScheduleResponse putTripsByScheduleItem(String key, Integer tripsByScheduleItem) {
    if (this.tripsBySchedule == null) {
      this.tripsBySchedule = new HashMap<>();
    }
    this.tripsBySchedule.put(key, tripsByScheduleItem);
    return this;
  }

  /**
   * Get tripsBySchedule
   * @return tripsBySchedule
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TRIPS_BY_SCHEDULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Integer> getTripsBySchedule() {
    return tripsBySchedule;
  }


  @JsonProperty(JSON_PROPERTY_TRIPS_BY_SCHEDULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTripsBySchedule(@jakarta.annotation.Nullable Map<String, Integer> tripsBySchedule) {
    this.tripsBySchedule = tripsBySchedule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoScheduleResponse autoScheduleResponse = (AutoScheduleResponse) o;
    return Objects.equals(this.success, autoScheduleResponse.success) &&
        Objects.equals(this.message, autoScheduleResponse.message) &&
        Objects.equals(this.schedulesProcessed, autoScheduleResponse.schedulesProcessed) &&
        Objects.equals(this.tripsCreated, autoScheduleResponse.tripsCreated) &&
        Objects.equals(this.tripsBySchedule, autoScheduleResponse.tripsBySchedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, message, schedulesProcessed, tripsCreated, tripsBySchedule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoScheduleResponse {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    schedulesProcessed: ").append(toIndentedString(schedulesProcessed)).append("\n");
    sb.append("    tripsCreated: ").append(toIndentedString(tripsCreated)).append("\n");
    sb.append("    tripsBySchedule: ").append(toIndentedString(tripsBySchedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

