/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * CancelGroupRequestDTO
 */
@JsonPropertyOrder({
  CancelGroupRequestDTO.JSON_PROPERTY_BOOKING_ID,
  CancelGroupRequestDTO.JSON_PROPERTY_LOCK_GROUP_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CancelGroupRequestDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nullable
  private Long bookingId;

  public static final String JSON_PROPERTY_LOCK_GROUP_ID = "lockGroupId";
  @jakarta.annotation.Nullable
  private String lockGroupId;

  public CancelGroupRequestDTO() {
  }

  public CancelGroupRequestDTO bookingId(@jakarta.annotation.Nullable Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingId(@jakarta.annotation.Nullable Long bookingId) {
    this.bookingId = bookingId;
  }


  public CancelGroupRequestDTO lockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    
    this.lockGroupId = lockGroupId;
    return this;
  }

  /**
   * Get lockGroupId
   * @return lockGroupId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLockGroupId() {
    return lockGroupId;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    this.lockGroupId = lockGroupId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelGroupRequestDTO cancelGroupRequestDTO = (CancelGroupRequestDTO) o;
    return Objects.equals(this.bookingId, cancelGroupRequestDTO.bookingId) &&
        Objects.equals(this.lockGroupId, cancelGroupRequestDTO.lockGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, lockGroupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelGroupRequestDTO {\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    lockGroupId: ").append(toIndentedString(lockGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

