/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * ChatbotTripSearchRequest
 */
@JsonPropertyOrder({
  ChatbotTripSearchRequest.JSON_PROPERTY_ORIGIN,
  ChatbotTripSearchRequest.JSON_PROPERTY_DESTINATION,
  ChatbotTripSearchRequest.JSON_PROPERTY_DATE,
  ChatbotTripSearchRequest.JSON_PROPERTY_DEPARTURE_TIME_FROM,
  ChatbotTripSearchRequest.JSON_PROPERTY_DEPARTURE_TIME_TO,
  ChatbotTripSearchRequest.JSON_PROPERTY_ARRIVAL_TIME_FROM,
  ChatbotTripSearchRequest.JSON_PROPERTY_ARRIVAL_TIME_TO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ChatbotTripSearchRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ORIGIN = "origin";
  @jakarta.annotation.Nullable
  private String origin;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @jakarta.annotation.Nullable
  private String destination;

  public static final String JSON_PROPERTY_DATE = "date";
  @jakarta.annotation.Nullable
  private LocalDate date;

  public static final String JSON_PROPERTY_DEPARTURE_TIME_FROM = "departureTimeFrom";
  @jakarta.annotation.Nullable
  private String departureTimeFrom;

  public static final String JSON_PROPERTY_DEPARTURE_TIME_TO = "departureTimeTo";
  @jakarta.annotation.Nullable
  private String departureTimeTo;

  public static final String JSON_PROPERTY_ARRIVAL_TIME_FROM = "arrivalTimeFrom";
  @jakarta.annotation.Nullable
  private String arrivalTimeFrom;

  public static final String JSON_PROPERTY_ARRIVAL_TIME_TO = "arrivalTimeTo";
  @jakarta.annotation.Nullable
  private String arrivalTimeTo;

  public ChatbotTripSearchRequest() {
  }

  public ChatbotTripSearchRequest origin(@jakarta.annotation.Nullable String origin) {
    
    this.origin = origin;
    return this;
  }

  /**
   * Get origin
   * @return origin
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrigin() {
    return origin;
  }


  @JsonProperty(JSON_PROPERTY_ORIGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrigin(@jakarta.annotation.Nullable String origin) {
    this.origin = origin;
  }


  public ChatbotTripSearchRequest destination(@jakarta.annotation.Nullable String destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestination(@jakarta.annotation.Nullable String destination) {
    this.destination = destination;
  }


  public ChatbotTripSearchRequest date(@jakarta.annotation.Nullable LocalDate date) {
    
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(@jakarta.annotation.Nullable LocalDate date) {
    this.date = date;
  }


  public ChatbotTripSearchRequest departureTimeFrom(@jakarta.annotation.Nullable String departureTimeFrom) {
    
    this.departureTimeFrom = departureTimeFrom;
    return this;
  }

  /**
   * Get departureTimeFrom
   * @return departureTimeFrom
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDepartureTimeFrom() {
    return departureTimeFrom;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepartureTimeFrom(@jakarta.annotation.Nullable String departureTimeFrom) {
    this.departureTimeFrom = departureTimeFrom;
  }


  public ChatbotTripSearchRequest departureTimeTo(@jakarta.annotation.Nullable String departureTimeTo) {
    
    this.departureTimeTo = departureTimeTo;
    return this;
  }

  /**
   * Get departureTimeTo
   * @return departureTimeTo
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDepartureTimeTo() {
    return departureTimeTo;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepartureTimeTo(@jakarta.annotation.Nullable String departureTimeTo) {
    this.departureTimeTo = departureTimeTo;
  }


  public ChatbotTripSearchRequest arrivalTimeFrom(@jakarta.annotation.Nullable String arrivalTimeFrom) {
    
    this.arrivalTimeFrom = arrivalTimeFrom;
    return this;
  }

  /**
   * Get arrivalTimeFrom
   * @return arrivalTimeFrom
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArrivalTimeFrom() {
    return arrivalTimeFrom;
  }


  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArrivalTimeFrom(@jakarta.annotation.Nullable String arrivalTimeFrom) {
    this.arrivalTimeFrom = arrivalTimeFrom;
  }


  public ChatbotTripSearchRequest arrivalTimeTo(@jakarta.annotation.Nullable String arrivalTimeTo) {
    
    this.arrivalTimeTo = arrivalTimeTo;
    return this;
  }

  /**
   * Get arrivalTimeTo
   * @return arrivalTimeTo
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArrivalTimeTo() {
    return arrivalTimeTo;
  }


  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArrivalTimeTo(@jakarta.annotation.Nullable String arrivalTimeTo) {
    this.arrivalTimeTo = arrivalTimeTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatbotTripSearchRequest chatbotTripSearchRequest = (ChatbotTripSearchRequest) o;
    return Objects.equals(this.origin, chatbotTripSearchRequest.origin) &&
        Objects.equals(this.destination, chatbotTripSearchRequest.destination) &&
        Objects.equals(this.date, chatbotTripSearchRequest.date) &&
        Objects.equals(this.departureTimeFrom, chatbotTripSearchRequest.departureTimeFrom) &&
        Objects.equals(this.departureTimeTo, chatbotTripSearchRequest.departureTimeTo) &&
        Objects.equals(this.arrivalTimeFrom, chatbotTripSearchRequest.arrivalTimeFrom) &&
        Objects.equals(this.arrivalTimeTo, chatbotTripSearchRequest.arrivalTimeTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(origin, destination, date, departureTimeFrom, departureTimeTo, arrivalTimeFrom, arrivalTimeTo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatbotTripSearchRequest {\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    departureTimeFrom: ").append(toIndentedString(departureTimeFrom)).append("\n");
    sb.append("    departureTimeTo: ").append(toIndentedString(departureTimeTo)).append("\n");
    sb.append("    arrivalTimeFrom: ").append(toIndentedString(arrivalTimeFrom)).append("\n");
    sb.append("    arrivalTimeTo: ").append(toIndentedString(arrivalTimeTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

