/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msroute.client.model.RouteDTO;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PricingTemplateDTO
 */
@JsonPropertyOrder({
  PricingTemplateDTO.JSON_PROPERTY_ID,
  PricingTemplateDTO.JSON_PROPERTY_VEHICLE_TYPE,
  PricingTemplateDTO.JSON_PROPERTY_SEAT_TYPE,
  PricingTemplateDTO.JSON_PROPERTY_OCCASION_TYPE,
  PricingTemplateDTO.JSON_PROPERTY_BASE_FARE,
  PricingTemplateDTO.JSON_PROPERTY_VEHICLE_FACTOR,
  PricingTemplateDTO.JSON_PROPERTY_FLOOR_FACTOR,
  PricingTemplateDTO.JSON_PROPERTY_SEAT_FACTOR,
  PricingTemplateDTO.JSON_PROPERTY_OCCASION_FACTOR,
  PricingTemplateDTO.JSON_PROPERTY_FINAL_PRICE,
  PricingTemplateDTO.JSON_PROPERTY_VALID_FROM,
  PricingTemplateDTO.JSON_PROPERTY_VALID_TO,
  PricingTemplateDTO.JSON_PROPERTY_CREATED_AT,
  PricingTemplateDTO.JSON_PROPERTY_UPDATED_AT,
  PricingTemplateDTO.JSON_PROPERTY_IS_DELETED,
  PricingTemplateDTO.JSON_PROPERTY_DELETED_AT,
  PricingTemplateDTO.JSON_PROPERTY_DELETED_BY,
  PricingTemplateDTO.JSON_PROPERTY_ROUTE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PricingTemplateDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  /**
   * Gets or Sets vehicleType
   */
  public enum VehicleTypeEnum {
    STANDARD_BUS_VIP(String.valueOf("STANDARD_BUS_VIP")),
    
    STANDARD_BUS_NORMAL(String.valueOf("STANDARD_BUS_NORMAL")),
    
    LIMOUSINE(String.valueOf("LIMOUSINE"));

    private String value;

    VehicleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VehicleTypeEnum fromValue(String value) {
      for (VehicleTypeEnum b : VehicleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VEHICLE_TYPE = "vehicleType";
  @jakarta.annotation.Nonnull
  private VehicleTypeEnum vehicleType;

  /**
   * Gets or Sets seatType
   */
  public enum SeatTypeEnum {
    SLEEPER(String.valueOf("SLEEPER")),
    
    NORMAL(String.valueOf("NORMAL"));

    private String value;

    SeatTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SeatTypeEnum fromValue(String value) {
      for (SeatTypeEnum b : SeatTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SEAT_TYPE = "seatType";
  @jakarta.annotation.Nonnull
  private SeatTypeEnum seatType;

  /**
   * Gets or Sets occasionType
   */
  public enum OccasionTypeEnum {
    NORMAL(String.valueOf("NORMAL")),
    
    WEEKEND(String.valueOf("WEEKEND")),
    
    HOLIDAY(String.valueOf("HOLIDAY")),
    
    PEAK(String.valueOf("PEAK")),
    
    OFF_PEAK(String.valueOf("OFF_PEAK")),
    
    TET(String.valueOf("TET"));

    private String value;

    OccasionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OccasionTypeEnum fromValue(String value) {
      for (OccasionTypeEnum b : OccasionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OCCASION_TYPE = "occasionType";
  @jakarta.annotation.Nonnull
  private OccasionTypeEnum occasionType;

  public static final String JSON_PROPERTY_BASE_FARE = "baseFare";
  @jakarta.annotation.Nonnull
  private BigDecimal baseFare;

  public static final String JSON_PROPERTY_VEHICLE_FACTOR = "vehicleFactor";
  @jakarta.annotation.Nullable
  private BigDecimal vehicleFactor;

  public static final String JSON_PROPERTY_FLOOR_FACTOR = "floorFactor";
  @jakarta.annotation.Nullable
  private BigDecimal floorFactor;

  public static final String JSON_PROPERTY_SEAT_FACTOR = "seatFactor";
  @jakarta.annotation.Nullable
  private BigDecimal seatFactor;

  public static final String JSON_PROPERTY_OCCASION_FACTOR = "occasionFactor";
  @jakarta.annotation.Nonnull
  private BigDecimal occasionFactor;

  public static final String JSON_PROPERTY_FINAL_PRICE = "finalPrice";
  @jakarta.annotation.Nonnull
  private BigDecimal finalPrice;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  @jakarta.annotation.Nonnull
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  @jakarta.annotation.Nullable
  private LocalDate validTo;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_ROUTE = "route";
  @jakarta.annotation.Nonnull
  private RouteDTO route;

  public PricingTemplateDTO() {
  }

  public PricingTemplateDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public PricingTemplateDTO vehicleType(@jakarta.annotation.Nonnull VehicleTypeEnum vehicleType) {
    
    this.vehicleType = vehicleType;
    return this;
  }

  /**
   * Get vehicleType
   * @return vehicleType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_VEHICLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VehicleTypeEnum getVehicleType() {
    return vehicleType;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVehicleType(@jakarta.annotation.Nonnull VehicleTypeEnum vehicleType) {
    this.vehicleType = vehicleType;
  }


  public PricingTemplateDTO seatType(@jakarta.annotation.Nonnull SeatTypeEnum seatType) {
    
    this.seatType = seatType;
    return this;
  }

  /**
   * Get seatType
   * @return seatType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SEAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SeatTypeEnum getSeatType() {
    return seatType;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatType(@jakarta.annotation.Nonnull SeatTypeEnum seatType) {
    this.seatType = seatType;
  }


  public PricingTemplateDTO occasionType(@jakarta.annotation.Nonnull OccasionTypeEnum occasionType) {
    
    this.occasionType = occasionType;
    return this;
  }

  /**
   * Get occasionType
   * @return occasionType
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OCCASION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OccasionTypeEnum getOccasionType() {
    return occasionType;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionType(@jakarta.annotation.Nonnull OccasionTypeEnum occasionType) {
    this.occasionType = occasionType;
  }


  public PricingTemplateDTO baseFare(@jakarta.annotation.Nonnull BigDecimal baseFare) {
    
    this.baseFare = baseFare;
    return this;
  }

  /**
   * Get baseFare
   * @return baseFare
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_BASE_FARE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getBaseFare() {
    return baseFare;
  }


  @JsonProperty(JSON_PROPERTY_BASE_FARE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBaseFare(@jakarta.annotation.Nonnull BigDecimal baseFare) {
    this.baseFare = baseFare;
  }


  public PricingTemplateDTO vehicleFactor(@jakarta.annotation.Nullable BigDecimal vehicleFactor) {
    
    this.vehicleFactor = vehicleFactor;
    return this;
  }

  /**
   * Get vehicleFactor
   * @return vehicleFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_VEHICLE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVehicleFactor() {
    return vehicleFactor;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVehicleFactor(@jakarta.annotation.Nullable BigDecimal vehicleFactor) {
    this.vehicleFactor = vehicleFactor;
  }


  public PricingTemplateDTO floorFactor(@jakarta.annotation.Nullable BigDecimal floorFactor) {
    
    this.floorFactor = floorFactor;
    return this;
  }

  /**
   * Get floorFactor
   * @return floorFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_FLOOR_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFloorFactor() {
    return floorFactor;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFloorFactor(@jakarta.annotation.Nullable BigDecimal floorFactor) {
    this.floorFactor = floorFactor;
  }


  public PricingTemplateDTO seatFactor(@jakarta.annotation.Nullable BigDecimal seatFactor) {
    
    this.seatFactor = seatFactor;
    return this;
  }

  /**
   * Get seatFactor
   * @return seatFactor
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSeatFactor() {
    return seatFactor;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatFactor(@jakarta.annotation.Nullable BigDecimal seatFactor) {
    this.seatFactor = seatFactor;
  }


  public PricingTemplateDTO occasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    
    this.occasionFactor = occasionFactor;
    return this;
  }

  /**
   * Get occasionFactor
   * @return occasionFactor
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getOccasionFactor() {
    return occasionFactor;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    this.occasionFactor = occasionFactor;
  }


  public PricingTemplateDTO finalPrice(@jakarta.annotation.Nonnull BigDecimal finalPrice) {
    
    this.finalPrice = finalPrice;
    return this;
  }

  /**
   * Get finalPrice
   * @return finalPrice
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_FINAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getFinalPrice() {
    return finalPrice;
  }


  @JsonProperty(JSON_PROPERTY_FINAL_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFinalPrice(@jakarta.annotation.Nonnull BigDecimal finalPrice) {
    this.finalPrice = finalPrice;
  }


  public PricingTemplateDTO validFrom(@jakarta.annotation.Nonnull LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

  /**
   * Get validFrom
   * @return validFrom
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidFrom(@jakarta.annotation.Nonnull LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public PricingTemplateDTO validTo(@jakarta.annotation.Nullable LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

  /**
   * Get validTo
   * @return validTo
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(@jakarta.annotation.Nullable LocalDate validTo) {
    this.validTo = validTo;
  }


  public PricingTemplateDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PricingTemplateDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PricingTemplateDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public PricingTemplateDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public PricingTemplateDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public PricingTemplateDTO route(@jakarta.annotation.Nonnull RouteDTO route) {
    
    this.route = route;
    return this;
  }

  /**
   * Get route
   * @return route
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RouteDTO getRoute() {
    return route;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoute(@jakarta.annotation.Nonnull RouteDTO route) {
    this.route = route;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricingTemplateDTO pricingTemplateDTO = (PricingTemplateDTO) o;
    return Objects.equals(this.id, pricingTemplateDTO.id) &&
        Objects.equals(this.vehicleType, pricingTemplateDTO.vehicleType) &&
        Objects.equals(this.seatType, pricingTemplateDTO.seatType) &&
        Objects.equals(this.occasionType, pricingTemplateDTO.occasionType) &&
        Objects.equals(this.baseFare, pricingTemplateDTO.baseFare) &&
        Objects.equals(this.vehicleFactor, pricingTemplateDTO.vehicleFactor) &&
        Objects.equals(this.floorFactor, pricingTemplateDTO.floorFactor) &&
        Objects.equals(this.seatFactor, pricingTemplateDTO.seatFactor) &&
        Objects.equals(this.occasionFactor, pricingTemplateDTO.occasionFactor) &&
        Objects.equals(this.finalPrice, pricingTemplateDTO.finalPrice) &&
        Objects.equals(this.validFrom, pricingTemplateDTO.validFrom) &&
        Objects.equals(this.validTo, pricingTemplateDTO.validTo) &&
        Objects.equals(this.createdAt, pricingTemplateDTO.createdAt) &&
        Objects.equals(this.updatedAt, pricingTemplateDTO.updatedAt) &&
        Objects.equals(this.isDeleted, pricingTemplateDTO.isDeleted) &&
        Objects.equals(this.deletedAt, pricingTemplateDTO.deletedAt) &&
        Objects.equals(this.deletedBy, pricingTemplateDTO.deletedBy) &&
        Objects.equals(this.route, pricingTemplateDTO.route);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, vehicleType, seatType, occasionType, baseFare, vehicleFactor, floorFactor, seatFactor, occasionFactor, finalPrice, validFrom, validTo, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, route);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricingTemplateDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("    seatType: ").append(toIndentedString(seatType)).append("\n");
    sb.append("    occasionType: ").append(toIndentedString(occasionType)).append("\n");
    sb.append("    baseFare: ").append(toIndentedString(baseFare)).append("\n");
    sb.append("    vehicleFactor: ").append(toIndentedString(vehicleFactor)).append("\n");
    sb.append("    floorFactor: ").append(toIndentedString(floorFactor)).append("\n");
    sb.append("    seatFactor: ").append(toIndentedString(seatFactor)).append("\n");
    sb.append("    occasionFactor: ").append(toIndentedString(occasionFactor)).append("\n");
    sb.append("    finalPrice: ").append(toIndentedString(finalPrice)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

