/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msroute.client.model.ScheduleDTO;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * ScheduleTimeSlotDTO
 */
@JsonPropertyOrder({
  ScheduleTimeSlotDTO.JSON_PROPERTY_ID,
  ScheduleTimeSlotDTO.JSON_PROPERTY_SLOT_CODE,
  ScheduleTimeSlotDTO.JSON_PROPERTY_DEPARTURE_TIME,
  ScheduleTimeSlotDTO.JSON_PROPERTY_ARRIVAL_TIME,
  ScheduleTimeSlotDTO.JSON_PROPERTY_BUFFER_MINUTES,
  ScheduleTimeSlotDTO.JSON_PROPERTY_SEQUENCE,
  ScheduleTimeSlotDTO.JSON_PROPERTY_ACTIVE,
  ScheduleTimeSlotDTO.JSON_PROPERTY_CREATED_AT,
  ScheduleTimeSlotDTO.JSON_PROPERTY_UPDATED_AT,
  ScheduleTimeSlotDTO.JSON_PROPERTY_IS_DELETED,
  ScheduleTimeSlotDTO.JSON_PROPERTY_DELETED_AT,
  ScheduleTimeSlotDTO.JSON_PROPERTY_DELETED_BY,
  ScheduleTimeSlotDTO.JSON_PROPERTY_SCHEDULE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ScheduleTimeSlotDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_SLOT_CODE = "slotCode";
  @jakarta.annotation.Nonnull
  private String slotCode;

  public static final String JSON_PROPERTY_DEPARTURE_TIME = "departureTime";
  @jakarta.annotation.Nonnull
  private String departureTime;

  public static final String JSON_PROPERTY_ARRIVAL_TIME = "arrivalTime";
  @jakarta.annotation.Nonnull
  private String arrivalTime;

  public static final String JSON_PROPERTY_BUFFER_MINUTES = "bufferMinutes";
  @jakarta.annotation.Nullable
  private Integer bufferMinutes;

  public static final String JSON_PROPERTY_SEQUENCE = "sequence";
  @jakarta.annotation.Nullable
  private Integer sequence;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @jakarta.annotation.Nonnull
  private Boolean active;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_SCHEDULE = "schedule";
  @jakarta.annotation.Nonnull
  private ScheduleDTO schedule;

  public ScheduleTimeSlotDTO() {
  }

  public ScheduleTimeSlotDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ScheduleTimeSlotDTO slotCode(@jakarta.annotation.Nonnull String slotCode) {
    
    this.slotCode = slotCode;
    return this;
  }

  /**
   * Get slotCode
   * @return slotCode
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SLOT_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlotCode() {
    return slotCode;
  }


  @JsonProperty(JSON_PROPERTY_SLOT_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlotCode(@jakarta.annotation.Nonnull String slotCode) {
    this.slotCode = slotCode;
  }


  public ScheduleTimeSlotDTO departureTime(@jakarta.annotation.Nonnull String departureTime) {
    
    this.departureTime = departureTime;
    return this;
  }

  /**
   * Get departureTime
   * @return departureTime
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDepartureTime() {
    return departureTime;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureTime(@jakarta.annotation.Nonnull String departureTime) {
    this.departureTime = departureTime;
  }


  public ScheduleTimeSlotDTO arrivalTime(@jakarta.annotation.Nonnull String arrivalTime) {
    
    this.arrivalTime = arrivalTime;
    return this;
  }

  /**
   * Get arrivalTime
   * @return arrivalTime
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getArrivalTime() {
    return arrivalTime;
  }


  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArrivalTime(@jakarta.annotation.Nonnull String arrivalTime) {
    this.arrivalTime = arrivalTime;
  }


  public ScheduleTimeSlotDTO bufferMinutes(@jakarta.annotation.Nullable Integer bufferMinutes) {
    
    this.bufferMinutes = bufferMinutes;
    return this;
  }

  /**
   * Get bufferMinutes
   * @return bufferMinutes
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BUFFER_MINUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBufferMinutes() {
    return bufferMinutes;
  }


  @JsonProperty(JSON_PROPERTY_BUFFER_MINUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBufferMinutes(@jakarta.annotation.Nullable Integer bufferMinutes) {
    this.bufferMinutes = bufferMinutes;
  }


  public ScheduleTimeSlotDTO sequence(@jakarta.annotation.Nullable Integer sequence) {
    
    this.sequence = sequence;
    return this;
  }

  /**
   * Get sequence
   * @return sequence
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSequence() {
    return sequence;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSequence(@jakarta.annotation.Nullable Integer sequence) {
    this.sequence = sequence;
  }


  public ScheduleTimeSlotDTO active(@jakarta.annotation.Nonnull Boolean active) {
    
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActive(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
  }


  public ScheduleTimeSlotDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ScheduleTimeSlotDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ScheduleTimeSlotDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ScheduleTimeSlotDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ScheduleTimeSlotDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public ScheduleTimeSlotDTO schedule(@jakarta.annotation.Nonnull ScheduleDTO schedule) {
    
    this.schedule = schedule;
    return this;
  }

  /**
   * Get schedule
   * @return schedule
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_SCHEDULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ScheduleDTO getSchedule() {
    return schedule;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSchedule(@jakarta.annotation.Nonnull ScheduleDTO schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleTimeSlotDTO scheduleTimeSlotDTO = (ScheduleTimeSlotDTO) o;
    return Objects.equals(this.id, scheduleTimeSlotDTO.id) &&
        Objects.equals(this.slotCode, scheduleTimeSlotDTO.slotCode) &&
        Objects.equals(this.departureTime, scheduleTimeSlotDTO.departureTime) &&
        Objects.equals(this.arrivalTime, scheduleTimeSlotDTO.arrivalTime) &&
        Objects.equals(this.bufferMinutes, scheduleTimeSlotDTO.bufferMinutes) &&
        Objects.equals(this.sequence, scheduleTimeSlotDTO.sequence) &&
        Objects.equals(this.active, scheduleTimeSlotDTO.active) &&
        Objects.equals(this.createdAt, scheduleTimeSlotDTO.createdAt) &&
        Objects.equals(this.updatedAt, scheduleTimeSlotDTO.updatedAt) &&
        Objects.equals(this.isDeleted, scheduleTimeSlotDTO.isDeleted) &&
        Objects.equals(this.deletedAt, scheduleTimeSlotDTO.deletedAt) &&
        Objects.equals(this.deletedBy, scheduleTimeSlotDTO.deletedBy) &&
        Objects.equals(this.schedule, scheduleTimeSlotDTO.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slotCode, departureTime, arrivalTime, bufferMinutes, sequence, active, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, schedule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleTimeSlotDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slotCode: ").append(toIndentedString(slotCode)).append("\n");
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("    arrivalTime: ").append(toIndentedString(arrivalTime)).append("\n");
    sb.append("    bufferMinutes: ").append(toIndentedString(bufferMinutes)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

