/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msroute.client.model.RouteDTO;
import com.ridehub.feign.msroute.client.model.ScheduleOccasionDTO;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * ScheduleDTO
 */
@JsonPropertyOrder({
  ScheduleDTO.JSON_PROPERTY_ID,
  ScheduleDTO.JSON_PROPERTY_SCHEDULE_CODE,
  ScheduleDTO.JSON_PROPERTY_START_DATE,
  ScheduleDTO.JSON_PROPERTY_END_DATE,
  ScheduleDTO.JSON_PROPERTY_DAYS_OF_WEEK,
  ScheduleDTO.JSON_PROPERTY_ACTIVE,
  ScheduleDTO.JSON_PROPERTY_CREATED_AT,
  ScheduleDTO.JSON_PROPERTY_UPDATED_AT,
  ScheduleDTO.JSON_PROPERTY_IS_DELETED,
  ScheduleDTO.JSON_PROPERTY_DELETED_AT,
  ScheduleDTO.JSON_PROPERTY_DELETED_BY,
  ScheduleDTO.JSON_PROPERTY_OCCASION_RULE,
  ScheduleDTO.JSON_PROPERTY_ROUTE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ScheduleDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_SCHEDULE_CODE = "scheduleCode";
  @jakarta.annotation.Nonnull
  private String scheduleCode;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @jakarta.annotation.Nullable
  private LocalDate startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @jakarta.annotation.Nullable
  private LocalDate endDate;

  public static final String JSON_PROPERTY_DAYS_OF_WEEK = "daysOfWeek";
  @jakarta.annotation.Nullable
  private String daysOfWeek;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  @jakarta.annotation.Nonnull
  private Boolean active;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_OCCASION_RULE = "occasionRule";
  @jakarta.annotation.Nonnull
  private ScheduleOccasionDTO occasionRule;

  public static final String JSON_PROPERTY_ROUTE = "route";
  @jakarta.annotation.Nonnull
  private RouteDTO route;

  public ScheduleDTO() {
  }

  public ScheduleDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ScheduleDTO scheduleCode(@jakarta.annotation.Nonnull String scheduleCode) {
    
    this.scheduleCode = scheduleCode;
    return this;
  }

  /**
   * Get scheduleCode
   * @return scheduleCode
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SCHEDULE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getScheduleCode() {
    return scheduleCode;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScheduleCode(@jakarta.annotation.Nonnull String scheduleCode) {
    this.scheduleCode = scheduleCode;
  }


  public ScheduleDTO startDate(@jakarta.annotation.Nullable LocalDate startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * Get startDate
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@jakarta.annotation.Nullable LocalDate startDate) {
    this.startDate = startDate;
  }


  public ScheduleDTO endDate(@jakarta.annotation.Nullable LocalDate endDate) {
    
    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   * @return endDate
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(@jakarta.annotation.Nullable LocalDate endDate) {
    this.endDate = endDate;
  }


  public ScheduleDTO daysOfWeek(@jakarta.annotation.Nullable String daysOfWeek) {
    
    this.daysOfWeek = daysOfWeek;
    return this;
  }

  /**
   * Get daysOfWeek
   * @return daysOfWeek
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DAYS_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDaysOfWeek() {
    return daysOfWeek;
  }


  @JsonProperty(JSON_PROPERTY_DAYS_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDaysOfWeek(@jakarta.annotation.Nullable String daysOfWeek) {
    this.daysOfWeek = daysOfWeek;
  }


  public ScheduleDTO active(@jakarta.annotation.Nonnull Boolean active) {
    
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActive(@jakarta.annotation.Nonnull Boolean active) {
    this.active = active;
  }


  public ScheduleDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ScheduleDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ScheduleDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ScheduleDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ScheduleDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public ScheduleDTO occasionRule(@jakarta.annotation.Nonnull ScheduleOccasionDTO occasionRule) {
    
    this.occasionRule = occasionRule;
    return this;
  }

  /**
   * Get occasionRule
   * @return occasionRule
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OCCASION_RULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ScheduleOccasionDTO getOccasionRule() {
    return occasionRule;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_RULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionRule(@jakarta.annotation.Nonnull ScheduleOccasionDTO occasionRule) {
    this.occasionRule = occasionRule;
  }


  public ScheduleDTO route(@jakarta.annotation.Nonnull RouteDTO route) {
    
    this.route = route;
    return this;
  }

  /**
   * Get route
   * @return route
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RouteDTO getRoute() {
    return route;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoute(@jakarta.annotation.Nonnull RouteDTO route) {
    this.route = route;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleDTO scheduleDTO = (ScheduleDTO) o;
    return Objects.equals(this.id, scheduleDTO.id) &&
        Objects.equals(this.scheduleCode, scheduleDTO.scheduleCode) &&
        Objects.equals(this.startDate, scheduleDTO.startDate) &&
        Objects.equals(this.endDate, scheduleDTO.endDate) &&
        Objects.equals(this.daysOfWeek, scheduleDTO.daysOfWeek) &&
        Objects.equals(this.active, scheduleDTO.active) &&
        Objects.equals(this.createdAt, scheduleDTO.createdAt) &&
        Objects.equals(this.updatedAt, scheduleDTO.updatedAt) &&
        Objects.equals(this.isDeleted, scheduleDTO.isDeleted) &&
        Objects.equals(this.deletedAt, scheduleDTO.deletedAt) &&
        Objects.equals(this.deletedBy, scheduleDTO.deletedBy) &&
        Objects.equals(this.occasionRule, scheduleDTO.occasionRule) &&
        Objects.equals(this.route, scheduleDTO.route);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, scheduleCode, startDate, endDate, daysOfWeek, active, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, occasionRule, route);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    scheduleCode: ").append(toIndentedString(scheduleCode)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    daysOfWeek: ").append(toIndentedString(daysOfWeek)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    occasionRule: ").append(toIndentedString(occasionRule)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

