/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * ScheduleOccasionDTO
 */
@JsonPropertyOrder({
  ScheduleOccasionDTO.JSON_PROPERTY_ID,
  ScheduleOccasionDTO.JSON_PROPERTY_OCCASION,
  ScheduleOccasionDTO.JSON_PROPERTY_OCCASION_FACTOR,
  ScheduleOccasionDTO.JSON_PROPERTY_CREATED_AT,
  ScheduleOccasionDTO.JSON_PROPERTY_UPDATED_AT,
  ScheduleOccasionDTO.JSON_PROPERTY_IS_DELETED,
  ScheduleOccasionDTO.JSON_PROPERTY_DELETED_AT,
  ScheduleOccasionDTO.JSON_PROPERTY_DELETED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ScheduleOccasionDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  /**
   * Gets or Sets occasion
   */
  public enum OccasionEnum {
    NORMAL(String.valueOf("NORMAL")),
    
    WEEKEND(String.valueOf("WEEKEND")),
    
    HOLIDAY(String.valueOf("HOLIDAY")),
    
    PEAK(String.valueOf("PEAK")),
    
    OFF_PEAK(String.valueOf("OFF_PEAK")),
    
    TET(String.valueOf("TET"));

    private String value;

    OccasionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OccasionEnum fromValue(String value) {
      for (OccasionEnum b : OccasionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OCCASION = "occasion";
  @jakarta.annotation.Nonnull
  private OccasionEnum occasion;

  public static final String JSON_PROPERTY_OCCASION_FACTOR = "occasionFactor";
  @jakarta.annotation.Nonnull
  private BigDecimal occasionFactor;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public ScheduleOccasionDTO() {
  }

  public ScheduleOccasionDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ScheduleOccasionDTO occasion(@jakarta.annotation.Nonnull OccasionEnum occasion) {
    
    this.occasion = occasion;
    return this;
  }

  /**
   * Get occasion
   * @return occasion
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OCCASION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OccasionEnum getOccasion() {
    return occasion;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasion(@jakarta.annotation.Nonnull OccasionEnum occasion) {
    this.occasion = occasion;
  }


  public ScheduleOccasionDTO occasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    
    this.occasionFactor = occasionFactor;
    return this;
  }

  /**
   * Get occasionFactor
   * @return occasionFactor
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getOccasionFactor() {
    return occasionFactor;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    this.occasionFactor = occasionFactor;
  }


  public ScheduleOccasionDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ScheduleOccasionDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ScheduleOccasionDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ScheduleOccasionDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ScheduleOccasionDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleOccasionDTO scheduleOccasionDTO = (ScheduleOccasionDTO) o;
    return Objects.equals(this.id, scheduleOccasionDTO.id) &&
        Objects.equals(this.occasion, scheduleOccasionDTO.occasion) &&
        Objects.equals(this.occasionFactor, scheduleOccasionDTO.occasionFactor) &&
        Objects.equals(this.createdAt, scheduleOccasionDTO.createdAt) &&
        Objects.equals(this.updatedAt, scheduleOccasionDTO.updatedAt) &&
        Objects.equals(this.isDeleted, scheduleOccasionDTO.isDeleted) &&
        Objects.equals(this.deletedAt, scheduleOccasionDTO.deletedAt) &&
        Objects.equals(this.deletedBy, scheduleOccasionDTO.deletedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, occasion, occasionFactor, createdAt, updatedAt, isDeleted, deletedAt, deletedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleOccasionDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    occasion: ").append(toIndentedString(occasion)).append("\n");
    sb.append("    occasionFactor: ").append(toIndentedString(occasionFactor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

