/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msroute.client.model.PricingInfo;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SeatValidateLockResponseDTO
 */
@JsonPropertyOrder({
  SeatValidateLockResponseDTO.JSON_PROPERTY_STATUS,
  SeatValidateLockResponseDTO.JSON_PROPERTY_MESSAGE,
  SeatValidateLockResponseDTO.JSON_PROPERTY_LOCK_GROUP_ID,
  SeatValidateLockResponseDTO.JSON_PROPERTY_TRIP_ID,
  SeatValidateLockResponseDTO.JSON_PROPERTY_EXPIRES_AT,
  SeatValidateLockResponseDTO.JSON_PROPERTY_PRICING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatValidateLockResponseDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_LOCK_GROUP_ID = "lockGroupId";
  @jakarta.annotation.Nullable
  private String lockGroupId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nullable
  private Long tripId;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String JSON_PROPERTY_PRICING = "pricing";
  @jakarta.annotation.Nullable
  private PricingInfo pricing;

  public SeatValidateLockResponseDTO() {
  }

  public SeatValidateLockResponseDTO status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public SeatValidateLockResponseDTO message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public SeatValidateLockResponseDTO lockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    
    this.lockGroupId = lockGroupId;
    return this;
  }

  /**
   * Get lockGroupId
   * @return lockGroupId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLockGroupId() {
    return lockGroupId;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockGroupId(@jakarta.annotation.Nullable String lockGroupId) {
    this.lockGroupId = lockGroupId;
  }


  public SeatValidateLockResponseDTO tripId(@jakarta.annotation.Nullable Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTripId(@jakarta.annotation.Nullable Long tripId) {
    this.tripId = tripId;
  }


  public SeatValidateLockResponseDTO expiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public SeatValidateLockResponseDTO pricing(@jakarta.annotation.Nullable PricingInfo pricing) {
    
    this.pricing = pricing;
    return this;
  }

  /**
   * Get pricing
   * @return pricing
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PRICING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PricingInfo getPricing() {
    return pricing;
  }


  @JsonProperty(JSON_PROPERTY_PRICING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricing(@jakarta.annotation.Nullable PricingInfo pricing) {
    this.pricing = pricing;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatValidateLockResponseDTO seatValidateLockResponseDTO = (SeatValidateLockResponseDTO) o;
    return Objects.equals(this.status, seatValidateLockResponseDTO.status) &&
        Objects.equals(this.message, seatValidateLockResponseDTO.message) &&
        Objects.equals(this.lockGroupId, seatValidateLockResponseDTO.lockGroupId) &&
        Objects.equals(this.tripId, seatValidateLockResponseDTO.tripId) &&
        Objects.equals(this.expiresAt, seatValidateLockResponseDTO.expiresAt) &&
        Objects.equals(this.pricing, seatValidateLockResponseDTO.pricing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, lockGroupId, tripId, expiresAt, pricing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatValidateLockResponseDTO {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    lockGroupId: ").append(toIndentedString(lockGroupId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

