/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SeatHoldResponseDTO
 */
@JsonPropertyOrder({
  SeatHoldResponseDTO.JSON_PROPERTY_STATUS,
  SeatHoldResponseDTO.JSON_PROPERTY_MESSAGE,
  SeatHoldResponseDTO.JSON_PROPERTY_EXPIRES_AT,
  SeatHoldResponseDTO.JSON_PROPERTY_HELD_SEATS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatHoldResponseDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String JSON_PROPERTY_HELD_SEATS = "heldSeats";
  @jakarta.annotation.Nullable
  private List<String> heldSeats = new ArrayList<>();

  public SeatHoldResponseDTO() {
  }

  public SeatHoldResponseDTO status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public SeatHoldResponseDTO message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public SeatHoldResponseDTO expiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public SeatHoldResponseDTO heldSeats(@jakarta.annotation.Nullable List<String> heldSeats) {
    
    this.heldSeats = heldSeats;
    return this;
  }

  public SeatHoldResponseDTO addHeldSeatsItem(String heldSeatsItem) {
    if (this.heldSeats == null) {
      this.heldSeats = new ArrayList<>();
    }
    this.heldSeats.add(heldSeatsItem);
    return this;
  }

  /**
   * Get heldSeats
   * @return heldSeats
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_HELD_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getHeldSeats() {
    return heldSeats;
  }


  @JsonProperty(JSON_PROPERTY_HELD_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeldSeats(@jakarta.annotation.Nullable List<String> heldSeats) {
    this.heldSeats = heldSeats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatHoldResponseDTO seatHoldResponseDTO = (SeatHoldResponseDTO) o;
    return Objects.equals(this.status, seatHoldResponseDTO.status) &&
        Objects.equals(this.message, seatHoldResponseDTO.message) &&
        Objects.equals(this.expiresAt, seatHoldResponseDTO.expiresAt) &&
        Objects.equals(this.heldSeats, seatHoldResponseDTO.heldSeats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, expiresAt, heldSeats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatHoldResponseDTO {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    heldSeats: ").append(toIndentedString(heldSeats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

