/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SeatLockRequestDTO
 */
@JsonPropertyOrder({
  SeatLockRequestDTO.JSON_PROPERTY_BOOKING_ID,
  SeatLockRequestDTO.JSON_PROPERTY_TRIP_ID,
  SeatLockRequestDTO.JSON_PROPERTY_SEAT_NUMBERS,
  SeatLockRequestDTO.JSON_PROPERTY_IDEM_KEY,
  SeatLockRequestDTO.JSON_PROPERTY_HOLD_TTL_SEC,
  SeatLockRequestDTO.JSON_PROPERTY_USER_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatLockRequestDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nonnull
  private Long bookingId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private Long tripId;

  public static final String JSON_PROPERTY_SEAT_NUMBERS = "seatNumbers";
  @jakarta.annotation.Nullable
  private List<@Size(min = 1)String> seatNumbers = new ArrayList<>();

  public static final String JSON_PROPERTY_IDEM_KEY = "idemKey";
  @jakarta.annotation.Nullable
  private String idemKey;

  public static final String JSON_PROPERTY_HOLD_TTL_SEC = "holdTtlSec";
  @jakarta.annotation.Nullable
  private Integer holdTtlSec;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nullable
  private Long userId;

  public SeatLockRequestDTO() {
  }

  public SeatLockRequestDTO bookingId(@jakarta.annotation.Nonnull Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingId(@jakarta.annotation.Nonnull Long bookingId) {
    this.bookingId = bookingId;
  }


  public SeatLockRequestDTO tripId(@jakarta.annotation.Nonnull Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull Long tripId) {
    this.tripId = tripId;
  }


  public SeatLockRequestDTO seatNumbers(@jakarta.annotation.Nullable List<@Size(min = 1)String> seatNumbers) {
    
    this.seatNumbers = seatNumbers;
    return this;
  }

  public SeatLockRequestDTO addSeatNumbersItem(String seatNumbersItem) {
    if (this.seatNumbers == null) {
      this.seatNumbers = new ArrayList<>();
    }
    this.seatNumbers.add(seatNumbersItem);
    return this;
  }

  /**
   * Get seatNumbers
   * @return seatNumbers
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_SEAT_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Size(min = 1)String> getSeatNumbers() {
    return seatNumbers;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNumbers(@jakarta.annotation.Nullable List<@Size(min = 1)String> seatNumbers) {
    this.seatNumbers = seatNumbers;
  }


  public SeatLockRequestDTO idemKey(@jakarta.annotation.Nullable String idemKey) {
    
    this.idemKey = idemKey;
    return this;
  }

  /**
   * Get idemKey
   * @return idemKey
   */
  @jakarta.annotation.Nullable
 @Size(min=1)
  @JsonProperty(JSON_PROPERTY_IDEM_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdemKey() {
    return idemKey;
  }


  @JsonProperty(JSON_PROPERTY_IDEM_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdemKey(@jakarta.annotation.Nullable String idemKey) {
    this.idemKey = idemKey;
  }


  public SeatLockRequestDTO holdTtlSec(@jakarta.annotation.Nullable Integer holdTtlSec) {
    
    this.holdTtlSec = holdTtlSec;
    return this;
  }

  /**
   * Get holdTtlSec
   * @return holdTtlSec
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_HOLD_TTL_SEC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHoldTtlSec() {
    return holdTtlSec;
  }


  @JsonProperty(JSON_PROPERTY_HOLD_TTL_SEC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHoldTtlSec(@jakarta.annotation.Nullable Integer holdTtlSec) {
    this.holdTtlSec = holdTtlSec;
  }


  public SeatLockRequestDTO userId(@jakarta.annotation.Nullable Long userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@jakarta.annotation.Nullable Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatLockRequestDTO seatLockRequestDTO = (SeatLockRequestDTO) o;
    return Objects.equals(this.bookingId, seatLockRequestDTO.bookingId) &&
        Objects.equals(this.tripId, seatLockRequestDTO.tripId) &&
        Objects.equals(this.seatNumbers, seatLockRequestDTO.seatNumbers) &&
        Objects.equals(this.idemKey, seatLockRequestDTO.idemKey) &&
        Objects.equals(this.holdTtlSec, seatLockRequestDTO.holdTtlSec) &&
        Objects.equals(this.userId, seatLockRequestDTO.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, tripId, seatNumbers, idemKey, holdTtlSec, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatLockRequestDTO {\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    seatNumbers: ").append(toIndentedString(seatNumbers)).append("\n");
    sb.append("    idemKey: ").append(toIndentedString(idemKey)).append("\n");
    sb.append("    holdTtlSec: ").append(toIndentedString(holdTtlSec)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

