/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.feign.msroute.client.model.AttendantDTO;
import com.ridehub.feign.msroute.client.model.DriverDTO;
import com.ridehub.feign.msroute.client.model.PricingTemplateDTO;
import com.ridehub.feign.msroute.client.model.RouteDTO;
import com.ridehub.feign.msroute.client.model.ScheduleTimeSlotDTO;
import com.ridehub.feign.msroute.client.model.VehicleDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TripWithPricingDTO
 */
@JsonPropertyOrder({
  TripWithPricingDTO.JSON_PROPERTY_ID,
  TripWithPricingDTO.JSON_PROPERTY_TRIP_CODE,
  TripWithPricingDTO.JSON_PROPERTY_DEPARTURE_TIME,
  TripWithPricingDTO.JSON_PROPERTY_ARRIVAL_TIME,
  TripWithPricingDTO.JSON_PROPERTY_OCCASION_FACTOR,
  TripWithPricingDTO.JSON_PROPERTY_CREATED_AT,
  TripWithPricingDTO.JSON_PROPERTY_UPDATED_AT,
  TripWithPricingDTO.JSON_PROPERTY_IS_DELETED,
  TripWithPricingDTO.JSON_PROPERTY_DELETED_AT,
  TripWithPricingDTO.JSON_PROPERTY_DELETED_BY,
  TripWithPricingDTO.JSON_PROPERTY_ROUTE,
  TripWithPricingDTO.JSON_PROPERTY_VEHICLE,
  TripWithPricingDTO.JSON_PROPERTY_SLOT,
  TripWithPricingDTO.JSON_PROPERTY_DRIVER,
  TripWithPricingDTO.JSON_PROPERTY_ATTENDANT,
  TripWithPricingDTO.JSON_PROPERTY_PRICING_TEMPLATES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TripWithPricingDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_TRIP_CODE = "tripCode";
  @jakarta.annotation.Nonnull
  private String tripCode;

  public static final String JSON_PROPERTY_DEPARTURE_TIME = "departureTime";
  @jakarta.annotation.Nonnull
  private OffsetDateTime departureTime;

  public static final String JSON_PROPERTY_ARRIVAL_TIME = "arrivalTime";
  @jakarta.annotation.Nonnull
  private OffsetDateTime arrivalTime;

  public static final String JSON_PROPERTY_OCCASION_FACTOR = "occasionFactor";
  @jakarta.annotation.Nonnull
  private BigDecimal occasionFactor;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_ROUTE = "route";
  @jakarta.annotation.Nonnull
  private RouteDTO route;

  public static final String JSON_PROPERTY_VEHICLE = "vehicle";
  @jakarta.annotation.Nonnull
  private VehicleDTO vehicle;

  public static final String JSON_PROPERTY_SLOT = "slot";
  @jakarta.annotation.Nonnull
  private ScheduleTimeSlotDTO slot;

  public static final String JSON_PROPERTY_DRIVER = "driver";
  @jakarta.annotation.Nonnull
  private DriverDTO driver;

  public static final String JSON_PROPERTY_ATTENDANT = "attendant";
  @jakarta.annotation.Nullable
  private AttendantDTO attendant;

  public static final String JSON_PROPERTY_PRICING_TEMPLATES = "pricingTemplates";
  @jakarta.annotation.Nullable
  private List<@Valid PricingTemplateDTO> pricingTemplates = new ArrayList<>();

  public TripWithPricingDTO() {
  }

  public TripWithPricingDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TripWithPricingDTO tripCode(@jakarta.annotation.Nonnull String tripCode) {
    
    this.tripCode = tripCode;
    return this;
  }

  /**
   * Get tripCode
   * @return tripCode
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TRIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTripCode() {
    return tripCode;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripCode(@jakarta.annotation.Nonnull String tripCode) {
    this.tripCode = tripCode;
  }


  public TripWithPricingDTO departureTime(@jakarta.annotation.Nonnull OffsetDateTime departureTime) {
    
    this.departureTime = departureTime;
    return this;
  }

  /**
   * Get departureTime
   * @return departureTime
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDepartureTime() {
    return departureTime;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTURE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepartureTime(@jakarta.annotation.Nonnull OffsetDateTime departureTime) {
    this.departureTime = departureTime;
  }


  public TripWithPricingDTO arrivalTime(@jakarta.annotation.Nonnull OffsetDateTime arrivalTime) {
    
    this.arrivalTime = arrivalTime;
    return this;
  }

  /**
   * Get arrivalTime
   * @return arrivalTime
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getArrivalTime() {
    return arrivalTime;
  }


  @JsonProperty(JSON_PROPERTY_ARRIVAL_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArrivalTime(@jakarta.annotation.Nonnull OffsetDateTime arrivalTime) {
    this.arrivalTime = arrivalTime;
  }


  public TripWithPricingDTO occasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    
    this.occasionFactor = occasionFactor;
    return this;
  }

  /**
   * Get occasionFactor
   * @return occasionFactor
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getOccasionFactor() {
    return occasionFactor;
  }


  @JsonProperty(JSON_PROPERTY_OCCASION_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOccasionFactor(@jakarta.annotation.Nonnull BigDecimal occasionFactor) {
    this.occasionFactor = occasionFactor;
  }


  public TripWithPricingDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TripWithPricingDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TripWithPricingDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TripWithPricingDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TripWithPricingDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public TripWithPricingDTO route(@jakarta.annotation.Nonnull RouteDTO route) {
    
    this.route = route;
    return this;
  }

  /**
   * Get route
   * @return route
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RouteDTO getRoute() {
    return route;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoute(@jakarta.annotation.Nonnull RouteDTO route) {
    this.route = route;
  }


  public TripWithPricingDTO vehicle(@jakarta.annotation.Nonnull VehicleDTO vehicle) {
    
    this.vehicle = vehicle;
    return this;
  }

  /**
   * Get vehicle
   * @return vehicle
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_VEHICLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VehicleDTO getVehicle() {
    return vehicle;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVehicle(@jakarta.annotation.Nonnull VehicleDTO vehicle) {
    this.vehicle = vehicle;
  }


  public TripWithPricingDTO slot(@jakarta.annotation.Nonnull ScheduleTimeSlotDTO slot) {
    
    this.slot = slot;
    return this;
  }

  /**
   * Get slot
   * @return slot
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_SLOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ScheduleTimeSlotDTO getSlot() {
    return slot;
  }


  @JsonProperty(JSON_PROPERTY_SLOT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlot(@jakarta.annotation.Nonnull ScheduleTimeSlotDTO slot) {
    this.slot = slot;
  }


  public TripWithPricingDTO driver(@jakarta.annotation.Nonnull DriverDTO driver) {
    
    this.driver = driver;
    return this;
  }

  /**
   * Get driver
   * @return driver
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_DRIVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DriverDTO getDriver() {
    return driver;
  }


  @JsonProperty(JSON_PROPERTY_DRIVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDriver(@jakarta.annotation.Nonnull DriverDTO driver) {
    this.driver = driver;
  }


  public TripWithPricingDTO attendant(@jakarta.annotation.Nullable AttendantDTO attendant) {
    
    this.attendant = attendant;
    return this;
  }

  /**
   * Get attendant
   * @return attendant
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_ATTENDANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AttendantDTO getAttendant() {
    return attendant;
  }


  @JsonProperty(JSON_PROPERTY_ATTENDANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttendant(@jakarta.annotation.Nullable AttendantDTO attendant) {
    this.attendant = attendant;
  }


  public TripWithPricingDTO pricingTemplates(@jakarta.annotation.Nullable List<@Valid PricingTemplateDTO> pricingTemplates) {
    
    this.pricingTemplates = pricingTemplates;
    return this;
  }

  public TripWithPricingDTO addPricingTemplatesItem(PricingTemplateDTO pricingTemplatesItem) {
    if (this.pricingTemplates == null) {
      this.pricingTemplates = new ArrayList<>();
    }
    this.pricingTemplates.add(pricingTemplatesItem);
    return this;
  }

  /**
   * Get pricingTemplates
   * @return pricingTemplates
   */
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PRICING_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid PricingTemplateDTO> getPricingTemplates() {
    return pricingTemplates;
  }


  @JsonProperty(JSON_PROPERTY_PRICING_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricingTemplates(@jakarta.annotation.Nullable List<@Valid PricingTemplateDTO> pricingTemplates) {
    this.pricingTemplates = pricingTemplates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripWithPricingDTO tripWithPricingDTO = (TripWithPricingDTO) o;
    return Objects.equals(this.id, tripWithPricingDTO.id) &&
        Objects.equals(this.tripCode, tripWithPricingDTO.tripCode) &&
        Objects.equals(this.departureTime, tripWithPricingDTO.departureTime) &&
        Objects.equals(this.arrivalTime, tripWithPricingDTO.arrivalTime) &&
        Objects.equals(this.occasionFactor, tripWithPricingDTO.occasionFactor) &&
        Objects.equals(this.createdAt, tripWithPricingDTO.createdAt) &&
        Objects.equals(this.updatedAt, tripWithPricingDTO.updatedAt) &&
        Objects.equals(this.isDeleted, tripWithPricingDTO.isDeleted) &&
        Objects.equals(this.deletedAt, tripWithPricingDTO.deletedAt) &&
        Objects.equals(this.deletedBy, tripWithPricingDTO.deletedBy) &&
        Objects.equals(this.route, tripWithPricingDTO.route) &&
        Objects.equals(this.vehicle, tripWithPricingDTO.vehicle) &&
        Objects.equals(this.slot, tripWithPricingDTO.slot) &&
        Objects.equals(this.driver, tripWithPricingDTO.driver) &&
        Objects.equals(this.attendant, tripWithPricingDTO.attendant) &&
        Objects.equals(this.pricingTemplates, tripWithPricingDTO.pricingTemplates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tripCode, departureTime, arrivalTime, occasionFactor, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, route, vehicle, slot, driver, attendant, pricingTemplates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripWithPricingDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tripCode: ").append(toIndentedString(tripCode)).append("\n");
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("    arrivalTime: ").append(toIndentedString(arrivalTime)).append("\n");
    sb.append("    occasionFactor: ").append(toIndentedString(occasionFactor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("    vehicle: ").append(toIndentedString(vehicle)).append("\n");
    sb.append("    slot: ").append(toIndentedString(slot)).append("\n");
    sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
    sb.append("    attendant: ").append(toIndentedString(attendant)).append("\n");
    sb.append("    pricingTemplates: ").append(toIndentedString(pricingTemplates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

