/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.feign.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * VehicleTypeFactorUpdateDTO
 */
@JsonPropertyOrder({
  VehicleTypeFactorUpdateDTO.JSON_PROPERTY_TYPE,
  VehicleTypeFactorUpdateDTO.JSON_PROPERTY_TYPE_FACTOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class VehicleTypeFactorUpdateDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    STANDARD_BUS_VIP(String.valueOf("STANDARD_BUS_VIP")),
    
    STANDARD_BUS_NORMAL(String.valueOf("STANDARD_BUS_NORMAL")),
    
    LIMOUSINE(String.valueOf("LIMOUSINE"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_TYPE_FACTOR = "typeFactor";
  @jakarta.annotation.Nonnull
  private BigDecimal typeFactor;

  public VehicleTypeFactorUpdateDTO() {
  }

  public VehicleTypeFactorUpdateDTO type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public VehicleTypeFactorUpdateDTO typeFactor(@jakarta.annotation.Nonnull BigDecimal typeFactor) {
    
    this.typeFactor = typeFactor;
    return this;
  }

  /**
   * Get typeFactor
   * minimum: 0.0
   * @return typeFactor
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid
 @DecimalMin("0.0")
  @JsonProperty(JSON_PROPERTY_TYPE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTypeFactor() {
    return typeFactor;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeFactor(@jakarta.annotation.Nonnull BigDecimal typeFactor) {
    this.typeFactor = typeFactor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleTypeFactorUpdateDTO vehicleTypeFactorUpdateDTO = (VehicleTypeFactorUpdateDTO) o;
    return Objects.equals(this.type, vehicleTypeFactorUpdateDTO.type) &&
        Objects.equals(this.typeFactor, vehicleTypeFactorUpdateDTO.typeFactor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, typeFactor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleTypeFactorUpdateDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    typeFactor: ").append(toIndentedString(typeFactor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

